//
//  EnglishChemicalWordStore.m
//  BrainStorming
//
//  Created by 岡 大輔 on 2013/10/28.
//  Copyright (c) 2013年 岡 大輔. All rights reserved.
//

#import "EnglishChemicalWordStore.h"

@implementation EnglishChemicalWordStore

-(NSMutableArray *)GenerateWordArray
{
    NSMutableArray *ChemcalWordEn = [[NSMutableArray alloc] init];
    {
    NSArray *AWord = @[@"Abegg's Rule",@"Abhesive",@"Ablation",@"Absolute Alcohol",@"Absolute Pressure",
        @"Absolute Vacuum",@"Absolute Zero",@"Absolute Does",@"Absorption",@"Absorption Spectrum",
        @"Abundance Ratio",@"Acetal",@"Acid Anhydride",@"Acid Base Titration Definiation",
        @"Acid Dissociation Constant",@"Acid-Base Indicator",@"Acidic Solution",
        @"Acidulant",@"Acology",@"Acylic Faiber",@"Actinic",@"Actinides",@"Actinium",
        @"Activated Carbon",@"Activated Charcoal",@"Activated Complex",@"Activation Energy",
        @"Activity Series",@"Actual Yield",@"Acute Health Effect",@"Addition Polymer",
        @"Addition Reaction",@"Adhesive",@"Adsorption",@"Adulterant",@"Aeration",
        @"Aether",@"Air",@"Alcohol",@"Aldehyde",@"Aldoheptose",@"Aldohexose",@"Aldopentose",
        @"Aldose",@"Aldotetrose",@"Aldoxime",@"Algaecide",@"Aliphatic",@"Alipahatic Amino Acid",
        @"Aliphatic Compound",@"Aliphatic Group",@"Aliphatic Hydrocarbon",@"Alkaline",
        @"Alkaline Earth Metal",@"Alkenyl Group",@"Alkoxy Group",@"Alkyl Group",@"Alkylate",
        @"Alkylation",@"Allotrope",@"Alloy",@"Alpha Decay",@"Alpha Particle",@"Alpha Radiation",
        @"Alternating Copolymer",@"Aluminum",@"Amalgam",@"Americium",@"Amide",@"Amine",
        @"Ammeter",@"Ampere",@"Amphetamine",@"Amplitude",@"An Amino Acid",@"Anaerobic",
        @"Analyte",@"Angstrom",@"Angular Momentum Quantum Number",@"Anisotropy",
        @"Annealing",@"Anode",@"Anodize",@"Antibonding Orbital",@"Antichlor",
        @"Antiferromagnetism",@"Antimony",@"Aqua Fortis",@"Aqua Regia",@"Aqueous",
        @"Argentum",@"Argon",@"Arrhenius Acid",@"Arrhenius Base",@"Arrhenius Rate Equation",
        @"Arsenic",@"Aryl",@"Aryl Halide",@"Asbestos",@"Asphaltic",@"Asphalt",@"Asphyxiant",
        @"Astatine",@"Atactic",@"Atomosphere",@"Atomic Ion",@"Atto",@"Aurum",@"Austenite",
        @"Autoionization",@"Avogadro's Law",@"Azeotrope",@"Azide",@"Azimuthal Quantum Number",
        @"Azo Compound",@"Azo Group"];
    [ChemcalWordEn addObjectsFromArray:AWord];
        NSArray *BWord = @[@"BTU",@"Background Noise",@"Background Radiation",@"Bactericide",
        @"Baeyer Reagent",@"Band Gap Energy",@"Bar",@"Barium",@"Barometer",@"Barrel",
        @"Basic Anhydride",@"Batch Reactor",@"Battery",@"Bacquerel",@"Benzenoid Ring",
        @"Benzyl Group",@"Benzyne",@"Berkelium",@"Beryllium",@"Beta Decay",@"Beta Radiation",
        @"Bidentate",@"Bifunctional Monomer",@"Bimolecular",@"Binary Acid",@"Binary Compound",
        @"Biocide",@"Bioorganic Chemistry",@"Bismuth",@"Bitumen",@"Black Body",@"Black Body Radiation",
        @"Black Lead",@"Black Light",@"Black Copolymer",@"Blue Vitriol",@"Body Centered Cubic or BCC",
        @"Bohrium",@"Boltzmann's Constant",@"Bond Angle",@"Bond Dissociation Energy",
        @"Bond Energy",@"Bond Enthalpy",@"Bond Length",@"Bond Order",@"Bonding Molecular Orbital",
        @"Boron",@"Boyle's law",@"Branched Chain Alkane",@"Branched Polymer",@"Brass",
        @"Bremsstrahlung",@"Brimstone",@"British Thermal Unit",@"Bromination",@"Bromine",
        @"Bronsted-Lowry Acid",@"Bronsted-Lowry Base",@"Bronze",@"Butter",@"Butter of Antimony",
        @"Butter of Arsenic",@"Butter of Bismuth",@"Butter of Tin",@"Butter of Zinc",
        @"CFC",@"CGS Units",@"Cadmium",@"Caffeine",@"Calcium",@"Calibration",@"Californium",
        @"Calorimetry",@"Calx",@"Calx of Lead",@"Calx of Mercury",@"Candela",@"Capillary Action",
        @"Capsid",@"Capsomere",@"Carat",@"Carbanion",@"Carbenium",@"Carbocation",@"Carbon",
        @"Carbon-Carbon Bond",@"Carbon-Carbon Double Bond",@"Carbon-Carbon Triple Bond",
        @"Carbonate",@"Carbonium Ions",@"Carbonyl",@"Carbon Black",@"Carboxy-layse",
        @"Carboxyl Group",@"Carboxylation",@"Carboy",@"Carcinogen",@"Catabolism",@"Catalysis",
        @"Catalytic Cracking",@"Catenation",@"Cathode",@"Cathode Ray",@"Cation",@"Causality Principle",
        @"Cavitation",@"Ceiling Limit",@"Cell Potential",@"Celsius Temperature Scale",@"Centi",
        @"Ceramic",@"Cerium",@"Cesium",@"Cetane Number",@"Chain Molecule",@"Chain Reaction",
        @"Chaotropic",@"Charge",@"Charles's Law",@"Chelate",@"Chelation Agent",@"Chemical Change",
        @"Chemical Energy",@"Chemical Equilibrium",@"Chemical Formula",@"Chemical Kinetics",
        @"Chemical Property",@"Chemical Reaction",@"Chemical Symbol",@"Chemiluminescence",
        @"Cherenkov Radiation",@"Chlorate",@"Choride",@"Chlorinated Hydrocarbon",@"Chlorination",
        @"Chlorination Reaction",@"Chlorine",@"Chlorite",@"Chlorocarbon",@"Cholorofluorocarbon",
        @"Cholesteric",@"Chromate",@"Chromate Compound",@"Chromatography",@"Chromite",
        @"Chromium",@"Chromophore",@"Closed System",@"Cobalt",@"Coenzyme",@"Cohesion",
        @"Colloid",@"Columbium",@"Combination Reaction",@"Combined Gas Law",@"Combustion",
        @"Combustion Reaction",@"Common Name",@"Common-ion Effect",@"Complementarity Principle",
        @"Complete Combustion",@"Complex Ion",@"Composite Material",@"Compound",@"Comproportionation",
        @"Concentrated",@"Concentration",@"Condensation Polymer",@"Condensation Reaction",
        @"Condensed Formula",@"Conductor",@"Conformer",@"Congener",@"Conjugate",@"Conjugate Acid",
        @"Conjugate Base",@"Continuous Spectrum",@"Contributing Structure",@"Convection",
        @"Conversion Factor",@"Coordinate Bond",@"Coordination Complex",@"Coordination Number",
        @"Copernicium",@"Copolymer",@"Cropper",@"Corrosion",@"Corrosive",@"Coulomb",@"Coulomb's Law",
        @"Covalent Radius",@"Cracking",@"Critical Mass",@"Critical Point",@"Critical Pressure",
        @"Critical Temperature",@"Cross",@"Crown Ether",@"Cryogenic Gas",@"Cryogenics",
        @"Crystal Field Splitting",@"Crystallization Water",@"Crystallize",@"Crystals of Silver",
        @"Cubic Centimeter",@"Cupric",@"Cuprous",@"Cuprum",@"Curie",@"Curie Point",@"Curium",
        @"Current",@"Cyanate",@"Cyanide",@"Cycloalkane",@"Cycloalkene",@"Cysteine",@"Cystine"];
        [ChemcalWordEn addObjectsFromArray:BWord];
        NSArray *DWord = @[@"D Orbital",@"Dalton",@"Darmstadtium",@"Data",@"Dative Bond",@"Daughter Atom",
        @"Daughter Isotope",@"De Boglie Wavelength",@"Deaeration",@"Deca",@"Decantation",
        @"Decarboxylase",@"Decarboxylation",@"Decay Rate",@"Deci",@"Decoction",@"Decomposition Reaction",
        @"Definition of Frequency",@"Deflagration",@"Degenerate Orbitals",@"Degree",
        @"Dehydration Reation",@"Delocalized Electron",@"Delta Bond",@"Denaturant",
        @"Dependent Variable",@"Depolymerization",@"Derived Unit",@"Desalination",
        @"Desublimation",@"Deuteron",@"Dextrorotatory",@"Diastereomer",@"Diatomic",
        @"Diazo Compound",@"Diazonium Compound",@"Dichromate",@"Dichromate Compound",
        @"Didymium",@"Diene",@"Diffraction",@"Diketone",@"Dilution",@"Dimer",@"Diol",
        @"Dioxygenyl",@"Dipolar Bond",@"Dipole",@"Diprotic Acid",@"Dirac's Constant",
        @"Direct Proportion",@"Disaccharide",@"Displacement Reaction",@"Disproportionation",
        @"Dissociation Reaction",@"Distillation",@"Divalent",@"Divalent Anion",@"Divalent Cation",
        @"Double Replacement Reaction",@"Double Bond",@"Drug",@"Dry Cell",@"Dry Ice",
        @"Dubnium",@"Ductile",@"Dynamic Equilibrium",@"Dyne",@"Dysprosium",@"ELF",@"Earths",
        @"Effective Nuclear Charge",@"Einsteinium",@"Elastic",@"Elastic Limit",@"Elasticity",
        @"Elastomer",@"Electric Dipole",@"Electric Field",@"Electrical Conductivity",
        @"Electrical Resistivity",@"Electrochemical Cell",@"Electrode Potential",
        @"Electrokinetic Potential",@"Electromagnetic Radiation",@"Electromotive Force",
        @"Electron Capture",@"Electron Density",@"Electron Domain",@"Electron Shell",@"Electron Volt",
        @"Electrophile",@"Electroplating",@"Elementary Reaction",@"Elimination Reaction",
        @"Embittlement",@"Emission Spectrum",@"Emissions",@"Emissivity",@"Empirical Formula",
        @"Emulsifier",@"Emulsion",@"Endergonic",@"Energy Density",@"Enriched Uranium",
        @"Enthalpy",@"Enthalpy Change",@"Enthalpy of Atomization",@"Enthalpy of Fusion",
        @"Enthalpy of Reaction",@"Enthalpy of Vaporization",@"Enzyme",@"Epsom Salt",
        @"Equation of State",@"Equilibrium",@"Equilibrium Concentration",@"Equilibrium Constant",
        @"Equivalence Point",@"Erbium",@"Erg",@"Essential Amino Acid",@"Essential Oil",
        @"Ester",@"Ether",@"Ethyl Group",@"Europium",@"Exa",@"Excess Reactant",@"Excited State",
        @"Exergonic",@"Experimental Yield",@"Extensive Property",@"Extremely Low Frequency Radiation",
        @"F Orbital",@"Fahrenheit",@"Fahrenheit Temperature Scale",@"Family",@"Faraday Constant",
        @"Fat",@"Fatty Acid",@"Feedstock",@"Femto",@"Fermentation"];
        [ChemcalWordEn addObjectsFromArray:DWord];
        NSArray *FWord = @[@"Fermium",@"Ferrate",@"Ferric",@"Ferrous",@"Ferrum",@"Filtration",@"Fire",
        @"Fire Point",@"Fire Retardant",@"Flame Test",@"Flammable",@"Flash Point",
        @"Fluoridated Hydrocarbon",@"Fluorination",@"Fluorine",@"Fluorocarbon",@"Foam",
        @"Formal Charge",@"Formalin",@"Formation Reaction",@"Formula Mass",@"Francium",
        @"Free Electron",@"Free Energy",@"Friable",@"Fuel Cell",@"Full Range Naptha",
        @"Fullerene",@"Furanose"];
        [ChemcalWordEn addObjectsFromArray:FWord];
        NSArray *GWord = @[@"G",@"Gadolinium",@"Gallium",@"Gallon",@"Galvanic Cell",@"Galvanization",
            @"Galvanometer",@"Gasohol",@"Gauge Pressure",@"Gay",@"Gel",@"Germanium",@"Gibbs Free Energy",
            @"Giga",@"Glass Transition",@"Glycol",@"Glycosidic Bond",@"Gold",@"Grain Alcohol",
            @"Green Chemistry",@"Green Vitriol",@"Greenhouse Gas",@"HCFC",@"Hafnium",@"Half Reaction",
            @"Halide",@"Haloalcohol"];
        [ChemcalWordEn addObjectsFromArray:GWord];
        NSArray *HWord = @[@"Haloalkane",@"Haloarene",@"Halocarbon",@"Haloform",@"Halogenated Ether",
            @"Halogenated Hydrocarbon",@"Halogenation",@"Halogenoalkane",@"Halogenoarene",
            @"Halohydrin",@"Halon",@"Hapticity",@"Hard X-rays",@"Hartree",@"Hassium",@"Heat Capacity",
            @"Heat of Formation",@"Heat of Fusion",@"Heat of Sublimation",@"Heat of Vaporization",
            @"Heavy Metal",@"Heavy Naptha",@"Heavy Water",@"Hecto",@"Heisenberg Uncertainty Principle",
            @"Helium",@"Helmholtz Free Energy",@"Henderson Hasselbalch Equation",@"Henry's Law",
            @"Hepatic Air",@"Hepatotoxic",@"Hepatotoxin",@"Heptose",@"Herbicide",@"Hermetic Seal",
            @"Hertz",@"Hess's Law",@"Heteroatom",@"Heterocyclic Compound",@"Heterodimer",
            @"Heterogeneous",@"Heterogeneous Catalyst",@"Heterogeneous Mixture",@"Heterogeneous Reaction",
            @"Heteronuclear",@"Hexavalent",@"Hexose",@"Holmium",@"Homodimer",@"Homogeneous",
            @"Homogeneous Catalysis",@"Homonuclear",@"Homopolymer",@"Humidity",@"Hybrid Orbital",
            @"Hydrargyrum",@"Hydration Reaction",@"Hydride",@"Hydride Ion",@"Hydrochlorofluorocarbon",
            @"Hydrogen",@"Hydrogen Bond",@"Hydrolysis",@"Hydrometer",@"Hydrophilic",@"Hydrophobic",
            @"Hydroxide",@"Hydroxyl Group",@"Hygroscopic",@"Hypergolic",@"Hypertonic",@"Hyperchlorite",
            @"Hypothesis",@"Hypotonic",@"Lanthanum",@"Lattice Point",@"Law of Constant Composition",
            @"Law of Definite Proportions",@"Law of Multiple Proportions",@"Lawrencium",
            @"La Chatelier's Principle",@"Lead",@"Leclanche Cell",@"Levorotatory",@"Lewis Acid",
            @"Lewis Acid Base Reaction",@"Lewis Base",@"Lewis Complex",@"Lewis Structure",
            @"Ligand Field Splitting",@"Light Naptha",@"Limestone",@"Limiting Reactant"];
        [ChemcalWordEn addObjectsFromArray:HWord];
        NSArray *LWord = @[@"Liquefaction",@"Liter",@"Lithium",@"London Dispersion Force",@"Lone Pair",
            @"Lox",@"Lunar Caustic",@"Lunar Crystals",@"Lutetium",@"Lyase",@"Lye",@"Lyman Series",
            @"MSDS",@"MSG",@"Macromolecule",@"Magnesium",@"Magnetic Quantum Number",
            @"Main Group Elements",@"Manganese",@"Manometer",@"Mass Defect",@"Mass Excess",
            @"Mass Percentage",@"Mass Specific Heat Capacity",@"Mass Spectrometer",@"Mass Spectroscopy",
            @"Measurement",@"Medicinal Chemistry",@"Meitnerium",@"Mendelevium",@"Meniscus",
            @"Mer",@"Mercaptan",@"Mercapto Group",@"Mercury",@"Mesomerism",@"Meta",@"Metabolism",
            @"Metabolite",@"Metallic Character",@"Metallic Compounds",@"Metastable",@"Meter",
            @"Methyl",@"Methylene Group",@"Micro",@"Microbicide",@"Microgram",@"Microliter",
            @"Micrometer",@"Micron",@"Microwave",@"Milli",@"Milligram",@"Milliliter",
            @"Millimeter",@"Millimeters of Mercury",@"Mineral",@"Mineral Acid",@"Miscible",
            @"Mixture",@"Moderator",@"Mohs Scale",@"Moiety",@"Molality",@"Molar Enthalpy of Formation",
            @"Molar Enthalpy of Fusion",@"Molar Enthalpy of Vaporization",@"Molar Heat Capacity",
            @"Molar Mass",@"Molar Volume",@"Molarity",@"Molar",@"Mole",@"Mole Fraction",
            @"Mole Ratio",@"Molecular Equation",@"Molecular Formula",@"Molecular Geometry",
            @"Molecular Mass",@"Molecular Orbital",@"Molecular Sieve",@"Molecular Weight",
            @"Molecularity",@"Molecule",@"Molybdenum",@"Monatomic Ion",@"Monochromatic",
            @"Monodentate",@"Monomer",@"Monoprotic Acid",@"Monosaccharide",@"Mother Liquor",
            @"Multiple Bond",@"Muriatic Acid",@"Nano",@"Nanometer",@"Nanotechnology",
            @"Naphthalene",@"Naphtha",@"Naphthenes",@"Native Element",@"Natrium",@"Natural Abundance",
            @"Necrosis",@"Negatron",@"Nematic",@"Neodymium",@"Neon",@"Nephrotoxicant",
            @"Neptunium",@"Network Solid",@"Neurotoxicant",@"Neutrino",@"Neutron Emission",
            @"Newton",@"Nickel",@"Niobium",@"Nitrate",@"Nitrile",@"Nitrite",@"Nitro Compound",
            @"Nitro Group",@"Nitrogen",@"Nitrogenous Base",@"Nobelium",@"Noble Gas Core",
            @"Nonbonding Electron",@"Nonflammable",@"Nonoxidizing Acid",@"Nonvolatile",
            @"Normal Boiling Point",@"Normal Melting Point",@"Normality",@"Nuclear Binding Energy",
            @"Nuclear Fission",@"Nuclear Fusion",@"Nuclear Radiation",@"Nuclear Shell Model"];
        [ChemcalWordEn addObjectsFromArray:LWord];
        NSArray *NWord = @[@"Nucleation",@"Nucleic Acid",@"Nucleobase",@"Nucleon",@"Nuclephile",
            @"Nucleophilic Addition",@"Nucleoside",@"Nucleotide",@"Nucleotide Base",
            @"Nucleus",@"Nuclide",@"Null Hypothesis",@"Nurse Tank",@"Petroleum",@"RT",
            @"Racemic",@"Rad",@"Radian",@"Radiant Energy",@"Radiant Flux",@"Radiant Intensity",
            @"Radiation",@"Radiation Absorbed Does",@"Radical",@"Radio Waves",@"Radioactive",
            @"Radioactive Tracer",@"Radioactivity",@"Radiochemistry",@"Radioisotope",
            @"Radionuclide",@"Radium",@"Radon",@"Random Copolymer",@"Rankine",
            @"Rankine Temperature Scale",@"Raoult's Law",@"Rare Earth",@"Rare Earth Element",
            @"Rate Determining Step",@"Rayon",@"Reaction Coordinate",@"Reaction Quotient",
            @"Reaction Rate",@"Reagent",@"Real Gas",@"Rearangement Reaction",@"Receptor",
            @"Redox Indicator",@"Reductant",@"Reduction Agent",@"Reduction Half Reaction",
            @"Refrigerant",@"Regelation",@"Relative Density",@"Relative Error",@"Relative Standard Deviation",
            @"Relative Uncertainty",@"Rennet",@"Rennin",@"Residue",@"Resin",@"Reversible Reaction",
            @"Rhenium",@"Rhodium",@"Ring Molecule",@"Rodenticide",@"Roentgen",@"Roentgen Equivalent Man",
            @"Roentgenium",@"Rosin",@"Rubidium",@"Rubisco",@"Rust",@"Ruthenium",@"Rutherfordium",
            @"S Orbital",@"SI",@"Sal Ammoniac",@"Salfiable",@"Salifiable Earths",@"Salt Bridge",
            @"Salt of Tartar",@"Saltpeter",@"Samarium",@"Saturated Fat",@"Saturated Solution",
            @"Scalar",@"Scandium",@"Scientific Law",@"Seaborgium",@"Second",
            @"Second Quantum Number",@"Secondary Radiation",@"Selenium",@"Semi",
            @"Semipermeable Membrane",@"Sequestrant",@"Short",@"Side Chain",@"Sievert",
            @"Sigma Bond",@"Silica",@"Silicate",@"Silicon",@"Silver",@"Simple Protein",
            @"Simplest Formula",@"Single Bond",@"Single Displacement Reaction",@"Smectic",
            @"Smelting",@"Smog",@"Smoke",@"Soap",@"Soda Ash",@"Sodium",@"Soft X-rays",
            @"Sol",@"Solubility Product",@"Solute",@"Sorption",@"Specific Gas Constant",
            @"Specific Heat",@"Specific Heat Capacity",@"Specific Volume",@"Specific Weight",
            @"Spectator Ion",@"Spirit",@"Spirit of Alum",@"Spirit of Hartshorn",@"Spirit of Vitriol",
            @"Spontaneous Fission",@"Stabilizer",@"Standard Hydrogen Electrode",
            @"Standard Molar Entropy",@"Standard Oxication Potential",@"Standard Reduction Potential",
            @"Stannum",@"Starch",@"Stream",@"Stream Distillation",@"Stere",@"Stereochemistry",
            @"Stereoisomer",@"Steric Number",@"Sterling Silver",@"Sterol",@"Stibium",@"Stiffness",
            @"Stoichiometry",@"Strain",@"Strong Electrolyte",@"Strontium",@"Subatomic",
            @"Subshell",@"Substituent",@"Substitution Reaction",@"Substrate",@"Sugar",
            @"Sulfanyl Group",@"Sulfate",@"Sulfide",@"Sulfite",@"Sulfur",@"Superacid",
            @"Supercritical Fluid",@"Superoxide",@"Surface Tension",@"Surfactant",
            @"Suspension",@"Symproportionation",@"System Internationale",@"Tantalum",
            @"Tautomer",@"Technetium",@"Tellurium",@"Temperature",@"Tera",@"Terbium",
            @"Terminal Reaction",@"Terminus",@"Terpolymer",@"Tetrahedral",@"Tetrose",
            @"Thallium",@"Theoretical Yield",@"Theory",@"Thermal",@"Thermionic Emission",
            @"Thermodynamic Equilibrium",@"Thermodynamics",@"Thermoelectron",@"Thermometer",
            @"Thermometry",@"Thermoplastic",@"Thermoset",@"Thermosetting Plastic",
            @"Thiol"];
        [ChemcalWordEn addObjectsFromArray:NWord];
        NSArray *TWord = @[@"Thiol Group",@"Third Law of Thermodynamics",@"Thixotropic Fluid",
            @"Thorium",@"Thulium",@"Tin",@"Titanium",@"Titration",@"Torr",
            @"Total Angular Momentum Quantum Number",@"Trans Isomer",@"Transfer RNA",
            @"Translational Energy",@"Transuranium Element",@"Triangular Bipyramid",
            @"Triglyceride",@"Trihalomethane",@"Triose",@"Triple Bond",@"Tritium",@"Torr",
            @"Total Angular Momentum Quantum Number",@"Trans Isomer",@"Transfer RNA",
            @"Translational Energy",@"Transuranium Element",@"Triangular Bipyramid",@"Triglyceride",
            @"Trihalomethane",@"Triose",@"Triple Bond",@"Tritium",@"Troy Ounce",@"Tungsten",
            @"Tutty",@"Tyndall Effect",@"Ultra High Frequency",@"Ultra Low Frequency",
            @"Unimolecular Reaction",@"Unit",@"Universal Gas Constant",@"Universal Indicator",
            @"Universal Solvent",@"Unsaturated Fat",@"Unsaturated Solution",@"Ununhexium",
            @"Ununoctium",@"Ununpentium",@"Ununquadium",@"Ununseptium",@"Ununtrium",@"Uranuim",
            @"X Group",@"XanthophyⅡ",@"Yellowcake",@"Yield Strength",@"Yocto",@"Yotta",@"Mega"];
        [ChemcalWordEn addObjectsFromArray:TWord];

    }
    
    return ChemcalWordEn;
}

@end
