//
//  EnglishMedicalWordStore.m
//  BrainStorming
//
//  Created by 岡 大輔 on 2013/11/07.
//  Copyright (c) 2013年 岡 大輔. All rights reserved.
//

#import "EnglishMedicalWordStore.h"

@implementation EnglishMedicalWordStore

-(NSMutableArray *)GenerateWordArray
{
    NSMutableArray *MedicalWordStore = [[NSMutableArray alloc] init];
    NSArray *AWord = @[@"A",@"adenine",@"A-T",@"A.c.",@"AAA",@"AAAS",@"AAD",@"AAFP",@"American Academy of Family Physicians",
        @"AAMC",@"Ass Am Medical Colleges",@"AANAT",@"AAO",@"AAOS",@"American Academy of Orthopaedic Surgeons",
        @"AAP",@"ABG",@"Arterial blood gas",@"ABO blood group",@"ABR test",@"AC",@"AC joint",
        @"ACC",@"ACE2",@"angoitensin converting enzyme 2",@"ACEI",@"ACG2",@"ACL",@"ACL injury",
        @"ACOG",@"Amer College of Ob & Gyn",@"ACP",@"American College of Physicians",
        @"ACS",@"American College of Surgeons",@"ACh",@"acetylcholine",@"AchE",@"acetylcholinesterase",
        @"ADA",@"American Dental Association",@"ADA",@"American Diabetes Association",@"ADA deficiency",
        @"ADAMTS2",@"ADCC",@"antibody-dependent cell-mediated cytotox",@"ADD",@"attention deficit disorder",
        @"ADH",@"antidiuretic hormone",@"ADH secretion,inappropriate",@"ADI",@"ADLs",
        @"activities of daily living",@"ADU",@"AED",@"automated external defibrillator",
        @"AFAP",@"AFIP",@"AFO",@"ankle-foot orthosis",@"AFP",@"alpha-fetoprotein",@"AGXT",
        @"AHC",@"AHD",@"AID",@"artificial insemination by donor",@"AIDS wasting syndrome",
        @"AIDS-related complex",@"AIH",@"artificial insemination by husband",@"AK",
        @"AKA",@"above the knee amputation",@"AKU",@"ALA",@"ALCAM",@"ALMSI",@"ALPS",
        @"ALS",@"ALSI",@"ALS2",@"ALS3",@"ALS4",@"ALS5",@"ALS6",@"ALS7",@"ALS8",@"ALT",
        @"alanine aminotransferase",@"AMA",@"AMC",@"arthrogryposis multiplex congenita",
        @"AMD",@"AMI",@"AML1",@"AMS",@"acute mountain sickness",@"AMS",@"atypical measles syndrome",
        @"ANA",@"ANC",@"ANLL",@"ANUG",@"acute necrotizing ulcerative gingivitis",
        @"ANXA1",@"AOA",@"AOM",@"AP",@"AP",@"anteroposterior",@"AP,X-ray",@"APA",@"APC",
        @"APC",@"gene",@"APC",@"immunology",@"APC",@"medication",@"APLS",
        @"antiphospholipid antibody syndrome",@"AOM1",@"APO-1",@"APOA-Ⅰ",@"APOBEG3G",
        @"APS",@"autoimmune polyglandular syndrome",@"APTⅠ",@"AQP",@"ARD",@"ARM",@"ARMD",
        @"ARS",@"ART",@"antiretroviral therapy",@"ASA",@"drug caution code",@"ASCUS",@"ASD",
        @"ASL",@"ASOT",@"AST",@"AT",@"ATCC",@"American Type Culture Collection",@"ATG",@"ATM",
        @"ATN",@"ATP",@"ATSDR",@"AV",@"atrioventricular",@"AV node",@"AVM",@"AVN",@"AZT",
        @"Asrskog syndrome",@"Aarskog-Scott syndrome",@"Aase-Smith syndrome Ⅰ",@"Aase-Smith syndrome Ⅱ",
        @"Av ovo",@"Ab-",@"Abate",@"Abatement",@"Abdomen",@"Abdomen,acute",@"Abdominal",
        @"Abdominal aneurysm",@"Absominal aorta",@"Abdominal cavity",@"Abdominal guarding",
        @"Abdominal muscle deficiency syndrome",@"Abdominal muscles",@"Abducent nerve",
        @"Abduction",@"Abductor muscle",@"Aberration",@"Abiological",@"Abiotic",@"Abiotrophy",
        @"Ablate",@"Ablation",@"Ablation,endometrial",@"Abnormal",@"Abortifacient",@"Abortion",
        @"Abortion,artificial",@"Abortion,habitual",@"Abortion,induced",@"Abortion,multiple",
        @"Abortion,recurrent",@"Abortion,spontaneous",@"Abortion,therapeutic",@"Abortive",
        @"Abraham-man",@"Abrasion",@"Abrin",@"Abruptio",@"abruptio placentae",@"Abruption",
        @"Abs",@"Abscess",@"Abscess,perianal",@"Abscess,peritonsillar",@"Abscess,skin",
        @"Abscission",@"Abse",@"Abse,Dannie",@"Absence of the nipple",@"Absent eye",
        @"Absenteeism",@"Absinthe",@"Absinthism",@"Absolute CD4 count",@"Absolute neutrophil count",
        @"Absorb",@"Absorbed does",@"Absorption",@"Abstemious",@"Abstinence",@"Abstinence,periodic",
        @"Abuse,child",@"Abuse,elder",@"Abuse,emotional child",@"Abuse,physical child",
        @"Abuse,psychological child",@"Abuse,sexual child",@"Abuse,substance",@"Abuse,verbal child",
        @"Abuse inhalant",@"Acanthamoeba",@"Acanthosis nigricans",@"Acapnia",@"Acaricide",
        @"Acathisia",@"Acceptable daily intake",@"Access",@"Accessibility or services",
        @"Accessory",@"Accessory digestive organ",@"Accessory dwelling unit",@"Accessory nerve",
        @"Accessory neuropathy",@"Accessory placenta",@"Acclimatization to altitude",
        @"Accommodation",@"Accoucheur",@"Accoucheuse",@"Acellular",@"Acellular vaccine",
        @"Acentric chromosome",@"Aceruloplasminemia",@"Acetabular",@"Acetabular labrum",
        @"Acetabulum",@"Acetate",@"Acetic acid",@"Acetoacetate",@"Acetone",@"Acetyl CoA",
        @"Acetyl coenzyme A",@"Acetyl Phosphate",@"Acetylcholine",@"Acetylcholinesterase",
        @"Acetylcysteine",@"Achilles tendon",@"Achilles tendonitis",@"Achillobursitis",
        @"Achillodynia",@"Achlorhydria",@"Achondrogenesis",@"Achondrogenesis type Ⅱ",
        @"Achondrogenesis,Langer-Saldino type",@"Achondrogenesis-hypochondrogenesis,type Ⅱ",
        @"Achoo syndrome",@"Achromatopsia",@"Achromycin",@"Acid deposition",@"Acid phosphatase",
        @"Acid rain",@"Acid reflux",@"Amino acid",@"Bile Acid",@"Fatty Acid",@"Folic Acid",
        @"Nucleic Acid",@"Panthothenic Acid",@"Trans Fatty Acid",@"Acid-base balance",
        @"Acidophilus",@"Acidosis",@"Acinetobacter",@"Pulnibary Acinus",@"Acon-",@"Acoustic",
        @"Acoustic nerve",@"Acoustic neurinoma",@"Acoustic neurofibromatosis",@"Acoustic neuroma",
        @"Acquired",@"Acquired immunity",@"Acquired mutation",@"Acrocentric chromosome",
        @"Acrocephalosyndactyly",@"Acrochordon",@"Acrocyanosis",@"Acrodermatitis enteropathica",
        @"Acrodynia",@"Acromegaly",@"Acromioclavicular joint",@"Acromion",@"Acrophobia",
        @"Acrylamide",@"Actinic",@"Actinomycetes",@"Activated charcoal",
        @"Activated leukocyte cell adhension molecule",@"Active enthanasia",@"Active immunity",
        @"Activities of daily living",@"ADLs",@"Drug activity",@"Avu−",@"Visual Acuity test",
        @"Auditory Acuity",@"Visual Acuity",@"Acupressure",@"Acupuncturist",@"Acustimulation",
        @"Acute",@"Acute HIV infection",@"Acute abdomen",@"Acute brain dyndrome",@"Acute confusional state",
        @"Acute coronary syndromes",@"Acute epiglottitis",@"Acute idiopathic polyneuritis",
        @"Acute illness",@"Acute membranous gingibitis",@"Acute mountain sickness",@"AMS",
        @"Acute myocardial infarction",@"Acute necrotizing ulcerative gingivitis",
        @"ANUG",@"Acute otitis media",@"Acute pain",@"Acute phase protein",@"Acute phase reactant",
        @"Acute radiation syndrome",@"Acute renal failure",@"Acute rspiratory disease",
        @"Acute respiratory distress syndrome",@"Acute thrombocytopenic purpura",
        @"Acute tubular necrosis",@"Acute-phase protein",@"Acute-phase proteins",@"Acute-phase reactant",
        @"Ad lib",@"Ad-",@"Adam's apple",@"Adamantine",@"Adams-Stokes disease",@"Adapter protein",
        @"Addiction",@"Computer addiction",@"Additive genetic effects",@"Adducted thumbs with metal retardation",
        @"Adduction",@"Adductor muscle",@"Aden-",@"Adenine(A)",@"Adenitis",@"Adeno-",@"Adenocarcinoma",
        @"Adenoid cystic carcinoma",@"Adenoidectomy",@"Adenoiditis",@"Adenoids",@"Adenoma",
        @"Adenoma colon family history",@"Adenomatous polyposis coli",@"autosomal recessive",
        @"Adenomyoma",@"Adenomyomata",@"Adenomyosis",@"Adenomyosis uteri",@"Adenopathy"];
    [MedicalWordStore addObjectsFromArray:AWord];
    NSArray *AdWord = @[@"Adenosine",@"Adenosine deaminase",@"ADA",@"Adenosine deaminase deficiency",
        @"Adenosine triphosphate",@"Adenovirus",@"Adhesion",@"Adhesive capsulities",
        @"Adipocyte",@"Adioponectin",@"Adiopose",@"Adiopose most abundant gene transcript 1",
        @"Adjacent",@"Adjuvant",@"Adjuvant therapy",@"Admission",@"Admitting physician",
        @"Adnexa",@"Adoption medicine",@"Adrenal cortex",@"Adrenal failure",@"Adrenal gland",
        @"Adrenal medulla",@"Adrenaline",@"Adrenoleukodystrophy",@"Adult T-cell lymphoma",
        @"Adult respiratory distress syndrome",@"Adult-onset Still disease",@"Adult-onset diabetes",
        @"Advance directives",@"Advance grief",@"Advanced maternal age",@"Advanced paternal age",
        @"Adventitia",@"Adventitious",@"Adverse drug event",@"Adverse drug reaction",
        @"Adverse effect",@"Adverse event",@"Adverse reaction",@"aero-",@"Aer-",@"Aerobic",
        @"Aeromonas hydrophila",@"Aerophagia",@"Aerophobia",@"Aerosinusitis",@"Aerosol",
        @"Aerosolization",@"Aerospace medicine",@"Aerotitis",@"Aerotitis media",@"Aesculapius",
        @"Aetiology",@"Affect",@"Seasonal affective disorder",@"SAD",@"Afferent",
        @"afferent nerve",@"Afferent vessel",@"Affinity",@"Aflatoxin",@"African American",
        @"African sleeping sickness",@"African tapeworm",@"African trypanosomiasis",
        @"African-American",@"Afterbirth",@"Agammaglobulinemia",@"Age by decade",@"Age of father",
        @"Age of mother",@"Agency for Toxic Substances and Disease Registry",@"Agenesis",
        @"Agenesis of the corpus callosum",@"Agenesis of the gallbladder",@"Sacral Agenesis",
        @"Agent Orange",@"Anti-infective Agent",@"Antibiotic Agent",@"Antifungal Agent",
        @"Antihypertensive Agent",@"Antimicrobial Agent",@"Antiprotozoal Agent",@"Antiviral Agent",
        @"Tocolytic Agent",@"Ageusia",@"Aggressive",@"Agressive angiomyxoma",@"Aggressive lymphoma",
        @"Aging",@"National Institute on Aging",@"Agita",@"Agnate",@"Agnosia",@"Agonist",
        @"Agonist maintenance treatment",@"LHRH Agonist",@"Agranulocytosis",@"Infantile Genetic Agranulocytosis",
        @"Arbitration Agreement",@"Ague",@"Agyrophobia",@"Aicardi syndrome",@"Vibrotactile Aid",
        @"Ailurophobia",@"Air Bag",@"Air-conditioner lung",@"Airway",@"Airway obstruction",
        @"Akathisia",@"Akinesia",@"Akinetic",@"Akinetic mutism",@"Alagille syndrome",
        @"Alanine",@"Alanine aminotransferase",@"ALT",@"Alb-",@"Albert Sabin",@"Albinism",
        @"Albinism and hemorrhagic diathesis",@"Oculocutaneous Albinism",@"Albino",
        @"Albuginea",@"Albumen",@"Albumin",@"Albuminuria",@"Alcohol",@"Alcohol abuse",
        @"Alcohol poisoning",@"Alcoholics Anonymous",@"Alcoholism",@"Aldose reductase inhibitor",
        @"Aldosterone",@"Aldosteronism",@"Aldrin",@"Alembic",@"Aleut health",@"Alexander disease",
        @"Alexander technique",@"Alexia",@"Algia",@"Algophobia",@"Alice Stewart",
        @"Alice in Wonderland syndrome",@"Alien hand syndrome",@"Alienist",@"Alimentary",
        @"Alimentary canal",@"Alkaline phosphatase",@"Alkaloid",@"Vinca Alkaloid",
        @"Alkalosis",@"Alkyl group",@"Allele",@"Allelic",@"Allergen",@"Allergic contact dermatitis",
        @"Allergic granulomatosis",@"Allergic granulomatous angiitis",@"Allergic purpura",
        @"Allergic rhinitis",@"Perennial Allergic rhinitis",@"Seasonal Allergic rhinitis",
        @"Allergic salute",@"Allodynia",@"Alloerotic",@"Allogeneic",@"Allogeneic graft",
        @"Allograft",@"Allopath",@"Allopathic",@"Allopathic medicine",@"Allopathist",
        @"Allopathy",@"Alogia",@"Alopecia",@"Alopecia capitis totalis",@"Alopecia universalis",
        @"Traumatic Alopecia",@"Alpers disease",@"Alpha Omega Alpha",@"Alpha blocker",
        @"Pancreatic Alpha cell",@"Alpha error",@"Alpha helix",@"Alpha linolenic acid",
        @"Alpha particle",@"Alpha synuclein",@"Alpha-1",@"Alpha−ET",@"Alpha-defensin",
        @"Alpha-ethltryptamine",@"Alpha-fetoprotein",@"AFP",@"Alpha-glucosidase inhibitor",
        @"Alpha-linolenic acid",@"Alport syndrome",@"Alstrom syndrome",@"Alstrom-Hallgren syndrome",
        @"Alternate hemiplegia",@"Alternating hemiplegia of childhood",@"Alternating hemiplegia syndrome",
        @"Alternative medical system",@"Alternative splicing",@"Altitude illness",@"Altitude sickness",
        @"Acclimatization to Altitude",@"High Altitude",@"Aluminum",@"Aluminum poisoning",
        @"Aluminum toxicity",@"Alveolar",@"Alveolar hydatid disease",@"Alveolar proteinosis",
        @"Alveoli",@"Alveolitis",@"Alveolus",@"Alzheimer disease",
        @"Early-onset familial Alzheimer disease",@"Alzheimer's disease",@"Am",@"Amalgam",
        @"Amastia",@"Amathophobia",@"Amaurosis fugax",@"Amaurotic familial idiocy",@"Amazia",
        @"Ambidextrous",@"Ambient",@"Ambiguous genitalia",@"Ambulance",@"Ambulant",@"Ambulatory",
        @"Ambulatory care",@"Ameba",@"Amebiasis",@"Amebic dysentery",@"Amelanotic",@"Amelioration",
        @"Amenia",@"Amer College of Ob and Gyn",@"ACOG",@"American Academy of Family Physicians",
        @"AAFP",@"American Academy of Orthopaedic Surgeons",@"American Academy of Pediatrics",
        @"American Association for Advancement of Science",@"American Association of Dermatology",
        @"American College of Nurse-Midwives",@"American College of Physicians",
        @"American College of Surgeons",@"ACS",@"American Dental Association",@"ADA",
        @"American Diabetes Association",@"American Journal of Public Health",
        @"American Medical Association",@"American Psychiatric Association",
        @"American Type Culture Collection",@"ATCC",@"American dog tick",@"First American Medical School",
        @"American trypanosomiasis",@"Americium",@"Ames test",@"Bruce N Ames",@"Amine",
        @"Amini",@"Fariborz Amini",@"Amino acid",@"Amino acid symbols",@"Branched-Chain amino acid",
        @"Essential amino acid",@"Nonessential Amino Acid",@"Amino Acids",@"Aminotransferase",
        @"Ammonia",@"Ammonium perchlorate",@"Amnesia",@"Antegrade Amnesia",@"Anterograde Amnesia",
        @"Retrograde Amnesia",@"Transient global amnesia",@"Amnion",@"Amnioreduction",
        @"Amniotic fluid",@"Amniotic sac",@"Amoeba",@"Amok",@"Amphetamine",@"Amplification",
        @"DNA Amplification",@"Ampulla",@"Ampulla of Vater",@"Ampullary carcinoma",
        @"Amputation",@"Amsler grid",@"Amuck",@"Amusia",@"Amygdala",@"Amygdaloid",@"Amygdaloid body",
        @"Amygdaloid complex",@"Amygdaloid nucleus",@"Amyl-",@"Amylase",@"Amylo-",
        @"Amyloid",@"An-",@"Anaerobic",@"Anaethesia",@"Anal atresia",@"Anal fistula",
        @"Anal incontinence",@"Anal papilla",@"Anal papillae",@"Analbuminemia",@"Analgesia",
        @"Analgesic",@"Analgesic drug",@"Analog",@"Analogous",@"Analysis",@"Linkage Analysis",
        @"Analytic sensitivity",@"Analytic specificity",@"Anaphia",@"Anaphylactoid purpura",
        @"Anaplasmosis",@"Anaplastology",@"Anaptic",@"Anastomosis",@"Anat",@"Anatomic orientation terms",
        @"Anatomical position",@"Anatomical snuffbox",@"Anatomy",@"Anatomy in the Bible",
        @"Gray's Anatomy",@"Gross Anatomy",@"Microscopic Anatomy",@"Anatripsis",@"Ancylostoma infection",
        @"Anderson-Fabry disease",@"Androgen",@"Androgen ablation",@"Complete Androgen insensitivity syndrome",
        @"Androgen suppression",@"Androgen suppression therapy",@"Androgenic",@"Android pelvis",
        @"Andrology",@"Androphobia",@"Androstenedione",@"Anemic",@"Anencephaly",@"Anergy",@"Anethesia",
        @"Anesthesia awareness",@"Caudal Epidural Anesthesia",@"Anesthesiologist",@"Anesthesiology",
        @"Anesthetic",@"Epidural Anesthetic",@"General Anesthetic",@"Local Anesthetic",
        @"Anesthetist",@"Anetoderma",@"Aneuploidy",@"Aneurysm",@"Abdominal Aneurysm",@"Aortic Aneurysm",
        @"Arterial Aneurysm",@"Arteriosclerotic Aneurysm",@"Atherosclerotic Aneurysm",
        @"Berry Aneurysm",@"Brain Aneurysm",@"Cardic Aneurysm",@"Dissecting Aneurysm",
        @"Fusiform Aneurysm",@"Miliary Aneurysm",@"Racemose Aneurysm",@"Renal Aneurysm",
        @"Saccular Aneurysm",@"Thoracic Aneurysm",@"Venous Aneurysm",@"Aneurysmal Bruit",
        @"Anfinsen",@"Anger",@"Angiitis",@"Allergic granulomatous Angiitis",@"Angioedema",
        @"Hereditary Angioedema",@"Angiogenesis",@"Angiogram",@"Angiography",@"Fluorescein Angiography",
        @"Angiohemophilia",@"Angioid streaks",@"Angiokeratoma corporis diffusum universale",
        @"Bacillary Angiomatosis",@"Aggressive Angiomyxoma",@"Angiopathy",@"Angioplasty",
        @"Angiosarcoma",@"Angiostatin",@"Angiostrongyliasis",@"Angiostrongylus infection",
        @"Angiotensin",@"Angiotensin converting enzyme",@"Angiotensin converting enzyme 2",
        @"Angiotensin receptor blocker",@"Angry",@"Anhedonia",@"Anhidrosis",@"Anhidrotic",
        @"Aniline",@"Animal-to-human transplant",@"Anion",@"Anion gap",@"Aniso",@"Aniso-",
        @"Anisocoria",@"Anisocytosis",@"Anisometropia",@"Ankle",@"Ankle bone",@"Ankle joint",
        @"Ankle sprain",@"Ankle twist",@"Ankle-foot orthosis",@"Ankyloglossia",@"Ankylose",
        @"Ankylosing",@"Ankylosis",@"Ankyrin deficiency",@"Anlage",@"Anlagen",@"Annals of Internal Medicine",
        @"Annexin A1",@"Annexin V",@"Annexins",@"Annotate",@"Annotation",@"Genome Annotation",
        @"Annular pancreas",@"Annulus",@"Anogenital Tract",@"Klippel-Feil Anomalad",@"Anomaly",
        @"Klippel-Feil Anomaly",@"Congenital Anomaly",@"Anomia",@"Anonymize",@"Anonymous reporting",
        @"Anonymous testing",@"Anophthalmia",@"Anorectic",@"Anorexia",@"Anorexic",@"Anorexigenic",
        @"Anorgasmia",@"Anorgasmy",@"Anoscope",@"Anoscopy",@"Anosmia",@"Anotia",@"Anovular",
        @"Anovulatory",@"Anoxia",@"Anoxic",@"Fire Ant",@"Antagonist",@"Antean",@"Antegrade",
        @"Antegrade amnesia",@"Antenatal surgery",@"Anterior",@"Anterior chamber",
        @"Anterior cruciate injury",@"Anterior cruciate ligament",@"Anterior pituitary",
        @"Anterior tongue",@"Antero-",@"Anterograde",@"Anterograde amnesia",@"Anterograde memory",
        @"Anteroposterior",@"Anteroposterior",@"AP",@"Anthophobia",@"Anthracycline",
        @"Forensic Anthropology",@"Anti CCP",@"Anti-",@"Anti-CCP",@"Anti-angiogenesis drug",
        @"Anti-cyclic citrullinated peptide antibody",@"Anti-emetic",@"Anti-infective",
        @"Anti-Platelet agents",@"Antiandrogen",@"Antiatherogenic mutation",@"Antibacterial",
        @"Antibiotic",@"Antibody",@"Antibody cross reactivity",@"Antinuclear Antibody",
        @"Antithyroglobulin Antibody",@"Antibody-dependent cell-mediated cytotoxicity",
        @"Anticholinergic",@"Antipation",@"Anticipatory grief",@"Anticoagulant",@"Anticoagulant agent",
        @"Anticonvulsant",@"Antidepressant",@"MAOI antidepressant",@"SSRI Antidepressant",
        @"Tricyclic antidepressant",@"Antidiabetic agent",@"Antidiuretic hormone",@"ADH",
        @"Antidote",@"Antielastase",@"Antiestogen",@"Antifreeze poisoning",@"Antifungal",
        @"Antifungal agent",@"Antifungal drug",@"Antifungal medication",@"Antigen",
        @"Prostate specific antigen",@"Antigen-antibody complex",@"Antigen-presenting cell",
        @"Antigenic drift",@"Antigenic shift",@"Antihistamines",@"Antihypertensive",
        @"Antiinfective",@"Antimalarial",@"Antimetabolite",@"Antimicrobial",@"Antimicrobial agent",
        @"Antimicrobial drug",@"Antimicrobial medication",@"Antimicrobial resistance",
        @"Antimony",@"Antineoplastic",@"Antioxident",@"Antiparallel",@"Antiparasitic",
        @"Antiprotozoal",@"Antiprotozoal drug",@"Antipsortiatic",@"Antipsychotic",@"Antipyretic",
        @"Antiretroviral",@"Antiretroviral therapy",@"ART",@"Antisense",@"Antisense DNA",
        @"Antisense drug",@"Antisense mRNA",@"Antisense-strand RNA virus",@"Antisepsis",
        @"Antiseptic",@"Antisocial personality",@"Antipasmodic",@"Antithymocyte globulin",
        @"Antithyroglobulin",@"Antithyroid antibody",@"Antithyroid drug",@"Antitoxin",
        @"Antivein",@"Antiviral",@"Antiviral agent",@"Anton Chekhow",@"Antonio Maria Valsava",
        @"Antonomasia",@"Antonomastic",@"Antonomasy",@"Antrum",@"Fire Ants",@"Velvet Ants",
        @"Anus",@"Imperforate anus",@"Anvil",@"Aorta",@"Abdominal aorta",@"Ascending aorta",
        @"Coarctation of the Aorta",@"Decending aorta",@"Thoracic aorta",@"Aortal",
        @"Aortic",@"Aortic aneurysm",@"Aortic arch",@"Aortic arch syndrome",@"Aortic atresia",
        @"Aoretic insufficiency",@"Aoretic regurgiation",@"Aoretic valve",@"Bicuspid Aortic valve",
        @"Aortitis",@"Aperient",@"Apert syndrome",@"Apert syndrome acrocephalosyndactyly",
        @"Apex",@"Apgar",@"Aphagia",@"Aphakia",@"Aphonia",@"Aphrasia",@"Aphthous ulcer",
        @"Apical",@"Apiphobia",@"Aplasia",@"Apnea",@"ApoA-Ⅰ Milano",@"Apolipoprotein A-Ⅰ",
        @"Apolipoprotein E",@"Apollo",@"Apopain",@"Apophenia",@"Apophysitis calcaneus",
        @"Apoplexy",@"Apoptosis",@"Appendiceal",@"Appendiceal perforation",@"Appendiceal rupture",
        @"Appendix",@"Appendix epididymis",@"Appendix epiploica",@"Appendix perforation",
        @"Appendix rupture",@"Appendix testis",@"Apposition",@"Approved drug",@"Apraxia",
        @"Apraxia of speech",@"Aquaphobia",@"Aquaporin",@"Aqueduct",@"Aqueduct of Sylvius",
        @"Aqueduct of the midbrain",@"Aqueous humor",@"Arabidopsis thaliana",
        @"Arabidopsis thaliana genome",@"Arachnodactyly",@"Arachnophobia",@"Arbitration agreement",
        @"Arboviral encephalitis",@"Arbovirus",@"Aortic arch",@"Vertebral arch",@"Zygomatic Arch",
        @"Archaea",@"Archaeogenetics",@"Archaeology",@"Arcuate neuron",@"Arcuate nucleus",
        @"Arcus senilis",@"Areflexia",@"Arenaviridae",@"Arenavirus",@"Areola",@"Argentaffinoma",
        @"Arginine",@"Argon laser",@"Argyria",@"Arhythmia",@"Arimidex",@"Aristolochia fangchi",
        @"Aristolochic acid",@"Aristotle",@"Arm",@"Armed Forces Institute of Pathology",
        @"Armed tapeworm",@"Arms",@"Aromasin",@"Aromatase",@"Aromatase inhibitor",@"Aromatherapy",
        @"Arrayed library",@"Arrector pili",@"Arrectores pilorum",@"Arrhythmia",@"Sinus arrhythmia",
        @"Atrial Arrhythmias",@"Rapid Arrhythmias",@"Alow arrhythmias",@"Ventricular arrhythmias",
        @"Arsine",@"Artemidorus",@"Artemisinin",@"Artemsisia annua",@"Arteria femoralis",
        @"Arterial aneurysm",@"Arterial blood gas",@"ABG",@"Arterial tension",@"Coronary arteries",
        @"Arteriogram",@"Arteriohepatic dysplasia",@"Arteriole",@"Arteriosclerosis",
        @"Arteriosclerotic aneurysm",@"Arteriosclerotic retinopathy",@"Takayasu arteritis",
        @"Cranial arteritis",@"Giant cell arteritis",@"Temporal arteritis",@"Artery",
        @"Coronary artery disease",@"Coronary artery spasm",@"Brachial artery",@"Carotid artery",
        @"Central Retinal artery",@"Femoral artery",@"Hepatic artery",@"Mesenteric Artery",
        @"Ophthalmic Artery",@"Pulmonary artery",@"Splenic artery",@"Vertebral artery",
        @"Arthr-",@"Arthralgia",@"Arthro-",@"Arthrocentesis",@"Arthrogryposis",
        @"Arthrogryposis multiplex congenita",@"AMC",@"Arthropathy",@"Arthroscope",
        @"Arthroscopic",@"Arthrosis",@"Artic health",@"Articulation",@"Articulation disorder",
        @"Principal articulation of the body",@"Artificial abortion",@"Artificial heart",
        @"Artificial insemination",@"Artificial insemination of donor",@"AID",
        @"Artificial insemination by husband",@"AIH",@"Artificial knee",@"Artificial nose",
        @"Artificial pancreas",@"Arylakylamine N-acetyltransferase",@"Asbestos",@"Asbestosis",
        @"Ascariasis",@"Ascaris",@"Ascending aorta",@"Ascending pathway",@"Asclepius",
        @"Ascorbic acid",@"Ascus",@"Asepic",@"Asexual",@"Asian flu",@"Asn",@"Asp",@"Asparagine",
        @"Aspartame",@"Aspartate aminotransferase",@"AST",@"Aspartic acid",@"Asperger's syndrome",
        @"Aspergillosis",@"Aspergillus",@"Asphyxia",@"Aspie",@"Aspirate",@"Aspiration",
        @"Fine needle aspiration",@"Joint aspiration",@"Aspirin",@"Aspirin resistance",
        @"Asplenia",@"Asplenic",@"Assay",@"CEA Assay",@"NSE Assay",@"Assembly and budding",
        @"DNA Assembly",@"Assignment of benefits",@"Assistant in dying",@"Physician assistant",
        @"PA",@"Assisted living",@"Assistive device",@"Assistive technology",@"Association",
        @"Association of American Medical Colleges",@"VATER association",@"Asthenia",
        @"Asthenic",@"Asthematic",@"Astigmatic",@"Astraphobia",@"Astrocytoma",@"Asymptomatic",
        @"Asymptomatic infection",@"Asystole",@"Ataxia",@"Ataxia telangiectasia mutated",
        @"Cerebellar ataxia",@"Ataxia-telagiectasia",@"Atelectasis",@"Primary atelectasis",
        @"Secondary atelectasis",@"Athelia",@"Atherectomy",@"Atherogenesis",@"Atheroma",
        @"Atherosclerosis",@"Atherosclerotic",@"Atherosclerotic aneurysm",@"Athetosis",
        @"Athleats feet",@"Athelete foot",@"Athelete's feet",@"Athymic",@"Athymic mouse",
        @"Atlantoaxial",@"Atlas",@"Altas and axis joint",@"Atoaxoid joint",@"Atom",
        @"Atonic",@"Atopic",@"Atopy",@"Atresia",@"Anal atresia",@"Aortic atresia",
        @"Biliary atresia",@"Atria",@"Atrial",@"Atrial arrhythmias",@"Atrial fib",
        @"Atrial flutter",@"Atrial septal defect",@"ASD",@"Atrial septum",@"Atriodigital dysplasia",
        @"Atriodigital dyplasia",@"Atrioventricular",@"AV",@"Atrioventricular node",
        @"Atrium",@"Atrophy",@"Peroneal muscular atrophy",@"Atropine",@"Atropine psychosis",
        @"Vasovagal attack",@"Attention",@"Attention deficit disorder",@"ADD",@"Attention getting",
        @"Attentional",@"Attenuate",@"Attenuated",@"Attenuated FAP",@"Attenuated familial adenomatous polyposis",
        @"Attenuated virus",@"Atypical",@"Atypical measles syndrome",@"AMS",@"Audiogram",
        @"Audiologist",@"Audiology",@"Audiometry",@"Auditory acuity",@"Auditory brainstem response test",
        @"Auditory cortex",@"Central auditory disease",@"Auditory integration training",
        @"Auditory perception",@"Auditory prosthesis",@"Auditory tube",@"Aura",@"Auricle",
        @"Auricular",@"Auscultate",@"Austin Flint murmur",@"Autism",@"Autistic savant",
        @"Autoantibody",@"Autochthonous",@"Autoclave",@"Autogenous",@"Autograft",@"Autoimmune",
        @"Autoimmune disease",@"Autoimmune lymphoproliferative syndrome",@"ALPS",@"Autoimmune polyendocrinopathy",
        @"Autoimmune polyendocrinopathy syndrome",@"Autoimmune polyglandular syndrome",@"APS",
        @"Autoimmune process",@"Autoimmunity",@"Autoinnoculation",@"Autologous",
        @"Autologous blood donation",@"Autolysis",@"Automated external defibrillator",
        @"Automated white cell differential",@"Automatic behavior",@"Automatism",@"Autonomic failure",
        @"Autonomic nervous system",@"Autonomic neuropathy",@"Patient autonomy",@"Autophobia",
        @"Autoradiography",@"Autosomal",@"Autosomal chromosome",@"Autosomal dominant",
        @"Autosomal dominant hereditary spastic paraplegia",@"Autosoal dominant radial drusen",
        @"Autosomal recessive",@"Autosome",@"Autotransplant",@"Autotransplantation",@"Aux-",
        @"Avacular nerosis",@"Avascular necrosis of the femoral head",@"Avery",@"Avian flu",
        @"Avulse",@"Avulsion",@"Avuncular",@"Axelrod",@"Julius Axelrod",@"computerized axial tomography",
        @"Axilla",@"Axillary",@"Axillary dissection",@"Axis",@"Axon",@"Ayurveda",@"Azoapwemia",
        @"Azotemia",@"B cell",@"B variant GM2-gangliosidosis",@"B virus",@"B(a)P",
        @"B-type natriuretic peptide",@"B.burgdorferi",@"B.capacia",@"B.coli",@"B.quintana",
        @"B.i.d(on prescription)",@"BAEP",@"brainstem auditory evoked potentials"];
    [MedicalWordStore addObjectsFromArray:AdWord];
    NSArray *BWord = @[@"BCC",@"BCG",@"BCM",@"BCNS",@"BDD",@"BER",@"BF",@"BIA",@"BIID",@"BKA",@"BLAST",
        @"BM",@"BMI",@"BMJ",@"BMP",@"BMP2",@"BMPR1A",@"BMRs",@"biological response modifiers",
        @"BMT",@"BNP",@"BOD POD",@"BP",@"BP1",@"BPD",@"BPH",@"BRCA1",@"BRCA2",@"BSA",@"BSL",
        @"BSL-1",@"BSL-2",@"BSL-3",@"BSL-4",@"BUN",@"BWS",@"BX",@"Ba",@"Babesiosis",@"Babinski reflex",
        @"Babinski response",@"Babinski sign",@"Baby blues",@"Baby teeth",@"Baby walker",
        @"Babysitter's elbow",@"Bacillary angiomatosis",@"Bacille calmette Guerin",
        @"Bacillophobia",@"Bacillus",@"Bacillus anthracis",@"Back pain",@"Low back pain",
        @"Backbone",@"Background radiation",@"Bacteremia",@"Bacteria",@"Bacterial",@"Bacterial artificial chromosome",
        @"Bacteriaphobia",@"Bacteriocidal",@"Bacteriology",@"Bacteriophage",@"Bacteriostatic",
        @"Bacterium",@"Air bag",@"Baker's yeast",@"Balance",@"Acid-base balance",@"Sense of balance",
        @"Balanitis",@"Circinate balanitis",@"Balanoposthitis",@"Balantidiasis",@"Balantidium",
        @"Baldness",@"Patchy baldness",@"Ball-and-socket joint",@"Balloon angioplasty",
        @"Baloon tamponade",@"Bambino",@"Ban zhi lian",@"Q band",@"Chromosome band",@"Banding of chromosomes",
        @"Bannayan syndrome",@"Bar chart",@"Bar Graph",@"Barbara McClintock",@"Barbat skullcap",
        @"Bariatric",@"Bariatric physician",@"Bariatric surgery",@"Bariatrician",@"Bariatrics",
        @"Barium",@"Barium solution",@"Barium swallow",@"Horace Albert Barker",@"Barlow syndrome",
        @"Baroparesis",@"Barosinusitis",@"Barotitis",@"Barotrauma",@"Optic barotrauma",
        @"Sinus barotrauma",@"Barr body",@"Bartholin's glands",@"Bartonella quintana",
        @"Bartter syndrome",@"Basal cell carcinoma",@"Basal cell nevus syndrome",@"Basal cells",
        @"Basal ganglia",@"Basal metabolic rate",@"Basal nuclei",@"Basal temperature",
        @"Basal thermometer",@"Base excision repair",@"Base in DNA",@"Base of tongue",
        @"Base pair",@"Base sequence",@"Base sequence analysis",@"Pressor base",@"Base-excision repair",
        @"Baseline",@"Basement membrane",@"Basic Local Alignment Search Tool",@"Basilar",
        @"Baskerville effect",@"Basophil",@"Basophilic leukocyte",@"Bather's eruption",
        @"Bathophobia",@"Battered child syndrome",@"Bayes theorem",@"Bayes'theorem",
        @"Baylisascaris",@"Beaded vitreous type Stickler syndrome",@"Beals",@"Rodney K. Beals",
        @"Beard",@"Premature Beat",@"Beau lines",@"Beau's lines",@"Beau-Reil cross furrows",
        @"Beaufort wind scale",@"Becker muscular dystrophy",@"Beckwith-Wiedemann syndrome",
        @"Bed blovker",@"Bed bug",@"Bed sore",@"Bednet",@"Bedsore",@"Bee genome",@"Africanized bee sting",
        @"Beef tapeworm",@"Beers criteria",@"Beers list",@"blister beetle",@"Moral behavior center",
        @"Behavior therapy",@"Automatic behavior",@"Behavioral medicine",@"Behcet's disease",
        @"Behcet's syndrome",@"Beijerinck",@"Martinus W. Beijerinck",@"Bekam",@"Belching",
        @"Bell",@"Bell's palsy",@"Charles Bell",@"Sir Charles Bell",@"Belladonna",@"Bellini duct carcinoma",
        @"Belly",@"Belly button",@"Belly pain",@"Seat Belt",@"Benign",@"Benign intracranial hypertension",
        @"Benign lymphoreticulosis",@"Benign prostatic hypertrophy",@"Benign recurrent aseptic meningitis",
        @"Benjamin Spock",@"Benzene",@"Benzidine",@"Benzoapyrene",@"Benzodiazepines",@"Bereacement",
        @"Bergamot oil",@"Bergstrom",@"Sune K Bergstrom",@"Beriberi",@"infantile beriberi",
        @"Berlin Heart",@"Bernard syndrome",@"Christiann Bernard",@"Bernard-Horner syndrome",
        @"Berstein test",@"Berry aueurysm",@"Berserk",@"Berylliosis",@"Beryllium",@"Berzelius",
        @"Jons Jacob Berzelius",@"Beta adrenergic blocking agents",@"Beta agonist",@"Beta blocker",
        @"Beta carotene",@"Beta cell",@"Pancreatic beta cell",@"Beta error",@"Beta particle",
        @"Beta protein 1",@"Beta-2 agonist",@"Beta-agonist",@"Beta-defensin",@"Beta-secretase",
        @"Betel nut",@"Beverly Hills diet",@"Bezoar",@"Bi-",@"Biallelic",@"Bias",@"Bicarbonate",
        @"Biceps",@"Bicornuate",@"Bicuspid",@"Bicuspid aortic valve",@"Bicuspid valve",@"Bicycle helmet",
        @"Bid(on prescription)",@"Bietti crystalline dystrophy",@"Bifid",@"Bifid uvula",
        @"Big bone disease",@"Big toe sign",@"Bilateral",@"Bile",@"Bile acid",@"Bile acid resin",
        @"Bile sludge",@"Bilhazia",@"Bilharziasis",@"Biliary",@"Biliary atresia",@"Biliary compression",
        @"Biliary decompression",@"Biliary",@"Biliary sludge",@"Bilious",@"Biliousness",
        @"Bilirubin",@"Biloma",@"Binaural",@"Binge drinking",@"Binocular",@"Binocular diplopia",
        @"Binocular vision",@"Binocularity",@"Binucleate",@"Bio-",@"Bioactive",@"Bioarchaeology",
        @"Biochemical",@"Biochemical aspirin resistance",@"Biochemistry",@"Bioelectric impedance analysis",
        @"Biofeedback",@"Biofilm",@"Biofluid",@"Bioinformatics",@"Biologic evolution",
        @"Biological chemistry",@"Biological response modifiers",@"Biological safety level 1",
        @"Biological safety level 2",@"Biological safety level 3",@"Biological safety level 4",
        @"Molecular biology",@"Biomagnetic therapy",@"Biomarker",@"Biopsy",@"Brain biopsy",
        @"Endometrial biopsy",@"Excisional biopsy",@"Incisional biopsy",@"Muscle biopsy",
        @"Punch biopsy",@"Sentinel-lymph-node biopsy",@"Skin biopsy",@"Strereotactic needle biopsy",
        @"Biosafety",@"Biosafety level",@"Biotechnology",@"Biotherapy",@"Biotin",@"Bipolar Ⅰ disorder",
        @"Bipolar Ⅱ disorder",@"Bipolar disease",@"Birt Hogg Dube syndrome",@"Birt-Hogg-Dube syndrome",
        @"Birth assistant",@"Birth cohort",@"Birth companion",@"Birth defect",@"Birth rate",
        @"Bis in die(on prescription)",@"Bisexual",@"Bisphosphonate",@"Biventricular assist device",
        @"Black American",@"Black Death",@"Black henna",@"Black lung disease",@"Blackhead",
        @"Elizabeth Blackwell",@"Bladder",@"Indwelling bladder catheter",@"Bladder inflammation",
        @"Bladder pain",@"Overactive bladder",@"Blade bone",@"Blalock-Taussig operation",
        @"Blast phase",@"Blastocyst",@"Blastocystis hominis",@"Blastocystis infection",
        @"Blastocystosis",@"Blastokinin",@"Blastoma",@"Blastomyces dermatitidis",@"Blastomycosis",
        @"Blasts",@"Bleb",@"Blender experiment",@"Blepharophimosis",@"Blepharoplasty",
        @"Blepharoptosis",@"Blepharospasm",@"Blighted ovum",@"Blind",@"Blind spot",@"Blinded study",
        @"Blister",@"Blister agent",@"Blister beetle",@"Blood blister",@"Fever blister",
        @"Water Blister",@"Blistering agent",@"Caudal block",@"Beta adrenergic blocker",
        @"Beta blockers",@"Blood",@"National Heart,Lung,and Blood Institute",@"Blood bank",
        @"Blood blister",@"Blood cleaner",@"Blood clot",@"Blood count",@"Blood culture",
        @"Blood draw",@"Blood dyscrasia",@"Blood group",@"ABO blood group",@"Blood in the eye",
        @"Blood pH",@"Blood poisoning",@"Blood pressure",@"High blood pressure",@"Low blood pressure",
        @"Blood sugar",@"High blood sugar",@"Low blood sugar",@"Blood urea nitrogen",@"Blood-brain barrier",
        @"Blood-thinner",@"Bloody nose",@"Bloody show",@"Bloody sputum",@"Northern blot",
        @"Southern blot",@"Western blot",@"Blue baby",@"Blue baby operation",@"Blue cohosh",
        @"Blueberry root",@"Blunted affect",@"Blurred vision",@"Blush",@"Board certified",
        @"Board eligible",@"Body cell mass",@"Body fat monitor",@"Body fat scales",
        @"Body habitus",@"Body hearing aid",@"Body image obsession",@"Body integrity identity disorder",
        @"Body mass index",@"Body odor",@"Body packer",@"Body packing",@"Body stuffing",@"Body surface area",
        @"Body type",@"Amygdaloid body",@"Ciliary body",@"Bodywork",@"Boerhaave's syndrome",
        @"Bogorad's syndrome",@"Bone",@"Aneurysmal bone cyst",@"Simple bone cyst",@"Bone density",
        @"Bone mass density",@"BMD",@"Bone mineral density",@"Bone morphogenetic protein",
        @"Bone morphogenic protein 2",@"Bone scan",@"Bone type",@"Ankle bone",@"Blade bone",
        @"Calf bone",@"Carpal bone",@"Coccygeal bone",@"Collar bone",@"Cranial bone",
        @"Cuboid bone",@"Endochondral bone",@"Ethmoid bone",@"Frontal Bone",@"Giant cell tumor of bone",
        @"Heel bone",@"Occipital bone",@"Parietal bone",@"Sesamoid Bone",@"Shin bone",
        @"Shenoid bone",@"Temporal bone",@"Thigh bone",@"Wing bone",@"Zygomatic bone",
        @"Bones of the arm,wrist and hand",@"Bones of the head",@"Bones of the leg,ankle and foot",
        @"Bones of the skeleton",@"Bones of the trunk",@"Axial bones",@"Bony syndactyly",
        @"Bony tarsus",@"Boomeritis",@"Booster shot",@"Borage",@"Borborygmi",@"Borborygmus",
        @"Bornholm disease",@"Borrelia",@"Borrelia burgdorferi",@"Bos taurus genome",
        @"Botox",@"Bottlefeeding",@"Botulinum toxin",@"Bougie",@"Bougienage",@"Boutonneuse",
        @"Bovine genome",@"Bow-legs",@"Bowel",@"Inflammatory bowel disease",@"Bowel sounds",
        @"Bowen disease",@"Bp",@"Milwaukee Brace",@"Foot-drop brace",@"Brachinal artery",
        @"Brachinal neuritis",@"Brachinal palsy",@"Brachinal paralysis",@"Brachinal plexus",
        @"Brachinal plexus palsy",@"Brachinal plexus paralysis",@"Brachial vein",
        @"Brachmann-de Lange syndrome",@"Brachy-",@"Brachycephaly",@"Brachydactyly",
        @"Bradycardia",@"Bradykinesia",@"Bradykinetic",@"Bradyphrenia",@"Bradypnea",
        @"Brailly system",@"Brain",@"Brain biopsy",@"Brain freeze",@"Brain malleability",
        @"Brain plasticity",@"Brain stem",@"Brain stem glioma",@"Brain swelling",@"Brain ventricle",
        @"Fornix of the brain",@"Water on the brain",@"Brainstem",@"Brainstem auditory evoked potentials",
        @"Brainstem implant",@"Branched-chain ketoaciduria",@"Branchial cleft cyst",
        @"Brazelton newborn test",@"Breadbasket",@"Breakbone fever",@"Breathing",@"Breech",
        @"Breech birth",@"Breslow thickness",@"Bridge",@"Bright's disease",@"Brill-Zinsser disease",
        @"Brissaud's infantilism",@"British National Formulary",@"Brittle bone disease",
        @"Brittle diabetes",@"Broca's area",@"Broken hip",@"Bromine",@"Bromism",@"Bromobenzylcyanide",
        @"Bromoderma",@"Bronchi",@"Bronchiole",@"Bronchiolitis",@"Bronchopulmonary",
        @"Bronchopulmonary dysplasia",@"Bronchopulmonary segments",@"Bronchoscope",@"Bronchus",
        @"Brontophobia",@"Bross",@"Irwin DJ Bross",@"Brown fat",@"Brown syndrome",@"Louise Brown",
        @"Michael Stuart Brown",@"Bruce N.Ames",@"Bruce protocol",@"Bruit",@"Brunhilde virus",
        @"Brushfield's spots",@"Bruton agammaglobulinemia tyrosine kinase",@"Bubble boy disease",
        @"Bubo",@"Buboes",@"Buccal mucosa",@"Buffalo chest",@"Buffalo hump",@"Kissing bug",
        @"Reduviid bug",@"Bullbar",@"Bullbar conjunctiva",@"Bulbourethral gland",@"Bulla",
        @"Bullae",@"Bullous",@"Bumps",@"Bundling",@"Buprenorphine",@"Burkholderia capacia",
        @"Burkitt lymphoma",@"Burkitt's lymphoma",@"Burning urination",@"Burp",@"Bursa",
        @"Bursae",@"Bursal",@"Bursopathy",@"Buruli ulcer",@"Buschke disease",@"Buschke scleredema",
        @"Buschke's disease",@"Buschke's scleredema",@"Butterbur",@"Butyric acid",@"Bx",@"Bypass"];
    [MedicalWordStore addObjectsFromArray:BWord];
    NSArray *CWord = @[@"Cardiopulmonary bypass",@"Coronary bypass",@"C(cytosine)",@"C peptide",@"C-IBS",
                       @"C-peptide",@"C-reactive protein",@"C.botulinum",@"C.difficile",@"C.elegans",
                       @"C.elegans genome",@"C.perfringens",@"C.welchii",@"C1(cervical vertebra)",
                       @"C1-C7(cervical vertebrae)",@"C2(cervical vertebra)",@"C3(cervical vertebra)",
                       @"C4(cervical vertebra)",@"C5(cervical vertebra)",@"C6(cervical vertebra)",
                       @"C7(cervical vertebra)",@"CA",@"CA 15-3",@"CA 19-9",@"CA 27-29",@"CABG",@"Off-pump CABG",
                       @"CAD",@"CADASIL",@"CADLLA",@"CAMP-dependent protein kinase",@"CAPD",@"CARDIA Study",
                       @"CB1",@"CB1 receptor",@"CB2",@"CB2 receptor",@"CBC",@"CBER",@"CBT",@"CC chemokine receptor 5",
    @"CCCR5",@"CCD",@"Central core disease of muscle",@"cleidocranial dysostosis",@"CCHF",
    @"CCK",@"CCL5",@"CCP",@"CCR5",@"CD10",@"CD4",@"Absolute CD4 count",@"CD40",@"CD8+ T cell",
    @"CD95",@"CDC",@"CDHR",@"CDNA",@"CEA",@"CEA assay",@"CEPH",@"CEPT",@"CF",@"CFS",@"CFTR",@"CHAMPUS",
    @"CHANGE association",@"CHANGE syndrome",@"CHD",@"CHEK2",@"CHF",@"CIC",@"CISM",@"CLA",@"CLIP",
    @"CLL",@"CM",@"coccidioidomycosis",@"CME",@"CMG2",@"CML",@"Juvenile CML",@"CMT",@"CNM",
    @"CNP",@"CNPs",@"CNR1",@"CNR2",@"CNS",@"central nervous system",@"CNS prophylaxis",
    @"COL4A5",@"COLD",@"chronic obstructive lung disease",@"COMT",@"CPAP",@"CPEO",
    @"CPEO with myopathy",@"CPEO with ragged-red fibers",@"CPM machine",@"CPP32",
    @"CPR",@"CRAC1",@"CRC",@"CREST syndrome",@"CRP",@"CSF",@"cerebrospinal fluid",@"colony-stimulating factor",
    @"CST3",@"CT",@"CT cell",@"CT colography",@"CT colonography",@"CT scan",@"Ultrafast CT",
    @"electron beam CT",@"CTL",@"CTS",@"CVA",@"CVC",@"CVS",@"CWD",@"CXCR4",@"Ca",@"Cabbage Soup Diet",
    @"Cachectic",@"Cachexia",@"Cadaver",@"Cadaver wart",@"Cadmium",@"Caduceus",@"Caecal",
    @"Caecum",@"Caenorhabditis elegans genome",@"Cafe au lait spot",@"Rib cage",@"Thoracic cage",
    @"Mark of cain",@"Cal",@"Paul Calabresi",@"Calamine",@"Calcaneal spur",@"Calcaneocuboid joint",
    @"Calcaneus",@"Calcification",@"Nonarteriosclerotic cerebral calcification",@"Calcified granuloma",
    @"Calcinosis",@"Calcipotriene",@"Calcitriol",@"Calcium",@"Calcium channel blocker",
    @"Calcium deficiency",@"Calcium excess",@"Calculi",@"Renal calculi",@"Calculus",@"Renal calculus",
    @"Calefacient",@"Calf",@"Calf bone",@"Caliciviridae",@"Calicivirius",@"Calipers",@"Skin calipers",
    @"Callosity",@"Callus",@"Calor",@"Calor,dolor,rubor, and tumor",@"Calorie",@"Camelpox",
    @"Camisole",@"Camphechlor",@"Thomas Campion",@"Campylobacter jejuni",@"Campylobacteriosis",
    @"Candida albicans",@"Candidate gene",@"Candidiasis",@"Invasive candidiasis",@"Oral Candidiasis",
    @"Canine genome",@"Canine heartworm",@"Cannabinoid",@"Cannabinoid receptor 1",@"Cannabinoid receptor 2",
    @"Cannabis",@"Cannonball pulse",@"Cannula",@"Capillaries",@"Capillary",@"Capillary morphogenesis gene 2",
    @"Capitation",@"Caps",@"Capaicin",@"Capsid",@"Capsule",@"Capsule of Glisson",@"Capsulitis",
    @"Captioning",@"Car booster seat",@"Carb",@"Carbo-loading",@"Carbohydrate",@"Infant carbohydrate intake",
    @"Carbohydrates",@"Carbolic acid",@"Carbon dioxide",@"Carbon dioxide content",@"Carbon monoxide on houseboats",
    @"Carbon monoxide poisoning",@"Carbonmonoxyhemoglobin",@"Carboxyhemoglobin",@"Carboxyhemoglobinemia",
    @"Carbuncles",@"Carcinogen",@"Carcinogenic",@"Carcinoid tumor",@"Carcinoma",@"Carcinoma in situ",
    @"Squamous cell carcinoma in situ",@"Carcinoma of the tongue",@"Markel cell carcinoma",
    @"Ampullary carcinoma",@"Basal cell carcinoma",@"hepatocellular carcinoma",@"islet cell carcinoma",
    @"Pancreatic carcinoma",@"Cardiac",@"Cardiac aneurysm",@"Cardiac conduction system",
    @"Implantable Cardiac defibrillator",@"Cardiac index",@"Cardiac insufficiency",@"Cardiac muscle",
    @"Cardiac myocyte",@"Cardiac myxoma",@"Cardiac output",@"Cardiac rehabilitation",
    @"Cardiac septum",@"Cardiac temponade",@"Cardiac transplant",@"Cardiac ventricle",
    @"Cardiac-limb syndrome",@"Cardio-cutaneous syndrome",@"Cardiologist",@"Cardiology",
    @"Cardiomegaly",@"Cardiomyopathy",@"Doxorubicin cardiomyopathy",@"Cardiopathy",@"Cardioplegia",
    @"Cardiopulmonary",@"Cardiopulmonary bypass",@"Cardiopulmonary resuscitation",
    @"Cardiovascular",@"Cardiovascular disease",@"Cardiovascular syncope",@"Cardiovascular system",
    @"Cardioversion",@"Cardioverter",@"Carditis",@"Health care proxy",@"Ambulatory care",
    @"Critical care",@"Managed care",@"Nail care",@"Postoperative care",@"Preoperative Care",
    @"Caries",@"Carminative",@"Carney complex",@"Beta carotene",@"Carotenemia",@"Carotenoid",
    @"Carotid",@"Carotid artery",@"Carotid body",@"Carotid endarterectomy",@"Carotid stenosis",
    @"Carotid-artery stenosis",@"Carpal bone",@"Carpal tunnel release",@"Carrier test",
    @"Cartilage",@"Cartilage hair hypoplasia syndrome",@"Casals-Ariet",@"Jordi Casals-Ariet",
    @"Cascade",@"Case-fatality percentage",@"Case-fatality proportion",@"Case-to-infection proportion",
    @"Case-to-infection ratio",@"Casein",@"Caseous",@"Caspase 3",@"Caspase-3",@"Cassette",
    @"Cast",@"Serial casting",@"Castleman disease",@"Castraction",@"Cat cry syndrome",
    @"Cat eye syndrome",@"Cat scratch fever",@"Catabolism",@"Catalepsy",@"Catalysis",
    @"Catalyst",@"Catamenia",@"Cataplasm",@"Cataplexy",@"Cataract with poikiloderma atrophicans",
    @"Nuclear cataract",@"Primary Cataract",@"Secondary cataract",@"Supranuclear cataract",
    @"Catatonic",@"Catechol-O-methyltransferase",@"Catecholamine",@"Cathartic",@"Catheter",
    @"Foley catheler",@"Swan-Ganz Catheter",@"Central catheter",@"Central venous catheter",
    @"Indwelling bladder catheter",@"Pulmonary artery catheter",@"Venous catheterization",
    @"Cathexis",@"Cation",@"Cauda equina",@"Caudad",@"Caudal",@"Caudal anesthesia",@"Caudal block",
    @"Caudal epidural anesthesia",@"Caudate nucleus",@"Caul",@"Caulophyllum thalictroides",
    @"Causalgia",@"Cauterization",@"Caveola",@"Cavernous hemangioma",@"Cavernous sinus",
    @"Cavernous sinus syndrome",@"Cavernous sinus thrombosis",@"Abdominal cavity",@"Cavy",
    @"Cecal",@"Cecal volvulus",@"Cecum",@"Celebrity diets",@"Celiac sprue",@"Cell",
    @"Cell cloning",@"Cell cycle",@"Cell fusion",@"Cell lineage",@"Fluorescence-activated cell sorter",
    @"Cell therapy",@"B cell",@"T cell",@"T-4 Cell",@"T-helper cell",@"Alpha pancreatic cell",
    @"Antigen-presenting cell",@"Beta pancreatic cell",@"Cone cell",@"Delta pancreatic cell",
    @"Fat cell",@"Helper cell",@"Plasma cell",@"Rod cell",@"Somatic cell",@"Stem cell",
    @"Totipotent cell",@"Cellophane maculopathy",@"Germ cells",@"Reproductive Cells",
    @"Cellulitus",@"Celsus",@"Cemento-ossifying fibroma",@"Centenarian",@"Center for Biologics Evaluation&Research",
    @"Center for Devices&Radiological Helth",@"Trauma center",@"Centigrade",@"Centimeter",
    @"Centimorgan",@"Central",@"Central auditory processing disorder",@"Central catheter",
    @"Central core disease",@"Central core disease of muscle",@"Central fovea",@"Central line",
    @"Central nervous system",@"CNS",@"Central retinal artery",@"Central retinal vein",
    @"Central venous catheter",@"Central venous line",@"Central vision",@"Centric-fusion translocation",
    @"Centromere",@"Cephal-",@"Cephalgia",@"Histamine cephalgia",@"Cephalic",@"Cephalic disorder",
    @"Cephalic disorders",@"Cephalothoracic lipodystrophy",@"Cerclage",@"Cercopithecine herpesvirus 1",
    @"Cerebellar",@"Cerebellum",@"Cerebral",@"Cerebral aneurysm",@"Cerebral arterial gas embolism",
    @"CAGE",@"Nonarteriosclerotic cerebral calcification",@"Cerebral cortex",@"Cerebral fornix",
    @"Cerebral hemispheres",@"Cerebral herniation",@"Cerebral vascular",@"Cerebral ventricle",
    @"Cerebritis",@"Cerebrohepatorenal syndrome",@"Cerebrospinal fluid",@"Cerebrovascular",
    @"Cerebrovascular accident",@"Cerebrovascular disease",@"Cerebrovascular ferrocalcinosis",
    @"Cerebrum",@"Certified midwife",@"Certified nurse-midwife",@"Certified professional midwife",
    @"Ceruloplasmin deficinecy",@"Cervical",@"Cervical cap",@"Cervical cerclage",@"Cervical disc",
    @"Cervical dystocia",@"Cervical intraepithelial neoplasia",@"Cervical rib",@"First cervical vertebra",
    @"Second cervical vertebra",@"Cervical vertebrae",@"Cervicectomy",@"Cervicitis",@"Cervix",
    @"Incompetent cervix",@"Lower segment cesarean section",@"Vaginal birth after Cesarean section",
    @"LSCS",@"Vaginal birth after cesarian section",@"Ceteris paribus",@"Chain-termination codon",
    @"anterior chamber",@"posterior chamber",@"Chamomile",@"Chancre",@"Chancroid",@"Chandipura virus",
    @"Change of life",@"Single base change",@"Ion channel",@"Channelopathy",@"Chaperone",
    @"Chapped lips",@"Char syndrome",@"Charbon",@"Activated charcoal",@"Charcot-Wilbrand syndrome",
    @"Chargaff ratios",@"Chargaff rule",@"Chargaff's rule",@"Charles Bell",@"Charles D.Kelman",
    @"Charles Darwin",@"Charley horse",@"Snellen's chart",@"Chasing the dragon",@"Checkpoint",
    @"Cheek",@"Cheilitis",@"Cheiroarthropathy",@"Chekhov",@"Anton Chekhov",@"Chemical reaction",
    @"Chemical terrorism",@"Chemo",@"Chemo-brain",@"Chemo-fog",@"Chemobrain",@"Chemoembolization",
    @"Chemofog",@"Chemokine",@"Chemokine receptor",@"Chemokinesis",@"Chemoprevention",@"Chemoprophylaxis",
    @"Chemoradiotherapy",@"Chemosense",@"Chemosensory",@"Chemosis",@"Zhong Wei Chen",@"Cherubism",
    @"Chest",@"Chest cold",@"Chest film",@"Chewing tobacco",@"Chicken genome",@"Chicken pox",
    @"Chickenpox immunization",@"Chickenpox vaccination",@"Chikungunya",@"Chilblain",@"Child development test",
    @"Child health",@"Mental child injury",@"Child neglect",@"Childbed fever",@"Childbirth assistant",
    @"Childbirth fever",@"Childhood",@"Childhood ataxia with CNS hypomyelinization",
    @"Children of the dark",@"Children of the night",@"Chills",@"Chimera",@"Chimeraplasty",
    @"Chin",@"Chinese medicine",@"Chinese restaurant syndrome",@"Chiron",@"Chiropractic",
    @"Chiropractor",@"Chlamydia",@"Chlamydia trachomatis",@"Chloral hydrate",@"Chloride",
    @"Chlorinated camphene",@"Chloroacetophenone",@"Chlorobenzylidenemalononitrile",
    @"Chloroform",@"Chloropicrin",@"Chloroprene",@"Chlorpyrifos",@"Choana",@"Choanae",
    @"Choanal",@"Choanal atresia",@"Choanal stenosis",@"Chocolate",@"Choking",
    @"Choking in children",@"Cholangi-",@"Cholangiogram",@"Ⅳ Cholangiogram",@"Intravenous cholangiogram",
    @"Cholangiography",@"Percutaneous transhepatic cholangiography",
    @"Endoscopic retrograde Cholangiopancreatography",@"Cholangitis",@"Primary sclerosing cholangitis",
    @"Sclerosing cholangitis",@"Cholecalciferol",@"Cholecyst",@"Cholecystitis",@"Oral cholecystogram",
    @"Cholecystokinin",@"Cholelithiasis",@"Cholestasis with peripheral pulmonary stenosis",
    @"Cholesteryl ester transfer protein",@"Cholestin",@"Chondrocalcinosis",@"Metaphyseal chondrodyplasia",
    @"Chondrodystrophic myotonia",@"Chondrogenesis imperfecta",@"Chondroitin sulfate",
    @"Chondromalacia",@"Chondromalacia patellae",@"Chondroplasia",@"Chondrosarcoma",
    @"Chorda tympani",@"Chordae tendineae",@"Chordoma",@"Chorea",@"Sydenham's chorea",
    @"Senile chorea",@"Chorioamnionitis",@"Placental chorioangioma",@"Choriocarcinoma",
    @"Chorion",@"human chorionic gonadotropin",@"Choroid",@"Choroiditis",@"Chrematophobia",
    @"Christian Boehmer Anfisen,Jr.",@"Chromaesthesia",@"Chromatids",@"Chromatin",@"Chromatin modeling",
    @"Chromatin remodeling",@"Gas chromatography",@"GC",@"Chromatophobia",@"Chromesthesia",
    @"Chromosome",@"Chromosome 1",@"Chromosome 2",@"Chromosome 3",@"Chromosome 4p- syndrome",
    @"Chromosome 5q- syndrome",@"Chromosome band",@"Chromosome banding",@"Chromosome complement",
    @"Chromosome disorder",@"Chromosome duplication",@"Chromosome inversion",
    @"Paracentric chromosome inversion",@"Pericentric chromosome inversion",@"Chromosome map",
    @"X chromosome",@"Y Chromosome",@"Acentric chromosome",@"Acrocentric chromosome",
    @"Dicentric chromosome",@"Marker chromosome",@"Metaphase chromosome",@"Chromosomes",
    @"Chromosomes in multiple miscarriages",@"Chronic",@"Global Initiativ Chronic Obstructive Lung Disease",
    @"Chronic disease",@"Chronic illness",@"Chronic obstructive lung disease",@"COLD",
    @"Chronic phase",@"Chronic progressive external ophthalmoplegia",@"Chronic renal failure",
    @"Chronic temponade",@"Chronic wasting disease",@"Chronicity",@"Chyle",@"Chylomicron",
    @"Chyme",@"Ci",@"Curie",@"Cidal",@"Cide",@"Cider vinegar diet",@"Cigar",@"Cigarette",
    @"Ciguatera",@"Ciguatoxin",@"Cilia",@"Ciliary body",@"Ciliary muscle",@"Ciliary neuralgia",
    @"Cilium",@"Cinacalcet",@"Circadian",@"Circinate balanitis",@"Circle of willis",@"Circular breathing",
    @"Circulation",@"Fetal circulation",@"Circulatory",@"Circulatory system",@"Circum-",
    @"Circumflex",@"Circumjacent",@"Cisplatin",@"Citrovorum factor",@"Citrulline",
    @"Civilian Health and Medical Program of the Uniform",@"Cl",@"chloride",@"Clade",
    @"Clamydia",@"Clap",@"Clark level of invasion",@"Clasped thumbs and mental retardation",
    @"Classification of diseases",@"Claustrophobia",@"Clavicle",@"Clavus",@"Cleft palate prosthesis",
    @"Cleft uvula",@"Cleidocranial dysostosis",@"Click-murmur syndrome",@"Climacteric",
    @"Clinical",@"Clinical Research Center",@"Clinical aspirin resistance",@"Clinical cytogenetics",
    @"Clinical disease",@"Clinical investigator",@"Clinical psychology",@"Clinical research trials",
    @"Licensed clinical social worker",@"Clinical trial",@"Clinodactyly",@"Clinophobia",
    @"Clip",@"Clitoral",@"Clitoral amputation",@"Clitorectomy",@"Clitoridectomy",@"Clitoris",
    @"Cloaca",@"Cloacal exstrophy",@"Clone",@"Clone bank",@"Recombinant clones",@"Cloning",
    @"Cloning vector",@"DNA Cloning",@"Cell cloning",@"Therapeutic cloning",@"Clonote",
    @"Clostridium",@"Clostridium botulinum",@"Clostridium difficile",@"Clostridium perfringens",
    @"Clostridium welchii",@"Blood clot",@"Clot-dissolving medication",@"Clotbuster",
    @"Club drug",@"Clubfoot",@"Cluster",@"Cm",@"centimeter",@"Co-morbid",@"Co-payment",
    @"Co-stimulation",@"CoQ10",@"Coagulation",@"Laser coagulation",@"Coal miner's pneumoconiosis",
    @"Coarctation",@"Coarctation of the aorta",@"Coated stent",@"Cobalamin",@"Cocci",
    @"Coccidiodomycosis",@"CM",@"Coccus",@"Coccygeal",@"Coccygeal vertebrae",@"Coccyx",
    @"Coccyx bone",@"Cochlea",@"Cochleae",@"Cochlear",@"Cochlear implant",@"Cockayne syndrome",
    @"Code",@"Code black",@"Code blue",@"Emergency code",@"Hospital code",@"Coding DNA",
    @"Codon",@"Coefficient of inbreeding",@"Coenzyme",@"Coenzyme Q10",@"Coeval",@"Coffin-Lowry syndrome",
    @"Cogan corneal dystrophy",@"Cogan syndrome",@"Cognition",@"Cognitive",@"Cognitive behavioral thrapy",
    @"Cognitive science",@"Cognitive therapy",@"Cognitive-behavioral therapy",@"Cohort",
    @"Cohort study",@"Coinsurance",@"Coitophobia",@"Coitus",@"Coitus interruptus",@"Cold injury",
    @"Common cold",@"Summer cold",@"Colectomy",@"Colinear",@"Colinearity",@"Collagen",@"Collagen Ⅳ alpha 5",
    @"Collagen disease",@"Collagen injection",@"type Ⅳ collagen alpha 5",@"Collagenopathy",
    @"Collapsed lung",@"Collapsing pulse",@"Collarbone",@"Collateral",@"Lateral collateral knee ligament",
    @"Medial Collateral knee ligament",@"Coloboma",@"Computed tomography colography",
    @"Colon",@"Colon polyp family history",@"Nervous colon syndrome",@"Colonic",@"Colonic adenoma family history",
    @"Colonoscope",@"Colony-stimulating factor",@"Color hearing",@"Eye color",@"Skin color",
    @"Colorblindness",@"Red-green colorblindness",@"Colorectal",@"Colorectal adenoma and carcinoma 1",
    @"Colorectal adenoma family history",@"Recessive colorectal adenomatous polyposis",
    @"Colorectal polyp",@"Colorectal surgeon",@"Coloscopy",@"Colostomy",@"Colostomy bag",
    @"iliac Colostomy",@"Transverse colostomy",@"Colostrum",@"Colpo-",@"Colpocephaly",
    @"Colpopexy",@"Colpoptosis",@"Colporrhaphy",@"Colposcope",@"Colpotomy",@"Combined oral contraceptive",
    @"Comedo",@"Comedones",@"Commensal",@"Common bilt duct",@"Common hepatic duct",
    @"Commotio cordis",@"Community-acquired infection",@"Comorbidity",@"Compassionate use",
    @"Complement system",@"Complementary DNA",@"Complementary medicine",@"Complementary sequence",
    @"Complete androgen intensitivity syndrome",@"Complete syndactyly",@"Complicated grief",
    @"Complication",@"Postoperative complications",@"Compound heterozygote",@"Compound microscope",
    @"Compress",@"Compression",@"Biliary compression",@"Nerve compression",@"Compulsive shopping",
    @"Computed tomography",@"Computed tomography colography",@"Computer addiction",
    @"Computerized axial tomography",@"CAT",@"Computerized axial tomography scan",
    @"Computerized tomography",@"Sir Arthur Conan Doyle",@"Concatemer",@"Concatenate",
    @"Conception",@"Concordance",@"Concordant",@"Concordant couple",@"Condition",@"Sever condition",
    @"Conditioning",@"Pavlovian conditioning",@"Female condom",@"Male condom",@"Cardiac conduction system",
    @"Condyloma",@"Condyloma acuminatum",@"Condyloma latum",@"Condyloma subcutaneum",
    @"Cone",@"Cone dystrophy",@"Cone snail",@"Congenital",@"Cogenital anomaly",@"Congenital arthrogryposis",
    @"Cogenital bilateral absence of vas deferens",@"Cogenital brevicollis",
    @"Congenital central hypoventilation syndrome",@"Congenital cervicothoracic vertebrae synostosis",
    @"Cogenital clasped thumb with mental retardation",@"Congenital defect",@"Congenital hip dislocation",
    @"Congenital malformation",@"Congenital osseus-torticollis syndrome",@"Congenital ptosis of the eyelids",
    @"Congenital retraction syndrome",@"Congenital rubella syndrome",
    @"Congenital synostosis of cervicothoracic vertebrae",@"Congenital torticollis",@"Congenital vaccinia",
    @"Congenital webbed neck syndrome",@"Congestion",@"Conization",@"Conjoined twin",
    @"Conjoined twins",@"Conjugated linoleic acid",@"Conjunctiva",@"Conjunctival",@"Conjunctival fornix",
    @"Allergic conjunctivitis",@"Conn syndrome",@"Connectionism",@"Connective tissue",
    @"Connexin",@"Connexin 26",@"Connexon",@"Conor and Bruch disease",@"Conotoxin",
    @"Consanguinity",@"Conservative mutation",@"Conserved sequence",@"Consolidation therapy",
    @"Constitutional thrombopathy",@"Constraint-induced movement therapy",@"Consultant",
    @"Consumption",@"Contact dermatitis",@"Allergic contact dermatitis",@"Contact healing",
    @"Contig",@"Contig map",@"Contiguous gene syndrome",@"Continuous passive motion machine",
    @"Continuous positive airway pressure",@"Emerygency contraception",@"Vaginal contraceptive sponge",
    @"Combined oral contraceptive",@"Implantable progestin contraceptive",@"Injectable progestin contraceptive",
    @"Minipill contraceptive",@"Pill contraceptive",@"Contraction",@"Premature contraction",
    @"Uterine contraction",@"Braxton Hicks Contractions",@"Contraindicate",@"Contraindication",
    @"Contralateral",@"Contrast",@"Contrast media",@"Contrast nephropathy",@"Visual contrast sensitivity",
    @"Control",@"Contusion",@"Convertional medicine",@"Convulsion",@"Coprolalia",@"Coprolith",
    @"Coprophobia",@"Copy number polymorphism",@"Cor",@"Cor bioculare",@"Cor pulmonale",
    @"Cord",@"Spinal cord",@"Umbilical cord",@"Vocal cord",@"Cordectomy",@"Corn",@"Cornea",
    @"Corneal",@"Corneal abrasion",@"Corneal dystrophy",@"Cogan corneal dystrophy",
    @"Fuchs endothelial corneal dystrophy",@"Epithelial basement corneal dystrophy",
    @"Lattics corneal dystrophy",@"Map-dot-fingerprint type corneal dystrophy",@"Microcystic corneal dystrophy",
    @"Intrastromal corneal ring",@"Corneal topography",@"Corneal transplant",@"Cornelia de Lange syndrome",
    @"Coronal",@"Coronary arteries",@"Coronary artery disease",@"Coronary artery spasm",
    @"Coronary bypass",@"Coronary insufficiency",@"Coronavirus",@"Corpora cavernosa",@"Corporeal",
    @"Corpse",@"Corpus",@"Corpus amygdaloideum",@"Corpus callosotomy",@"Agenesis of the corpus callosum",
    @"Corpus luteum cyst",@"Corrigan pulse",@"Cortex",@"Adrenal cortex",@"Cortical",@"Corticosteroid",
    @"Corticotropin-releasing hormone",@"Cortisol",@"Cortisone",@"Coryza",@"Cosmeceutical",
    @"Cosmid",@"Costal margin",@"Cotinine",@"Cotton rat",@"Cough",@"Cough suppressant",@"Coughing syncope",
    @"Coughing up blood",@"Teratogenicity of Coumadin",@"Genetic counseling",@"Genetic counselor",
    @"Absolute CD4 count",@"Platelet count",@"Geiger counter",@"Counterpulsation",@"Courier",
    @"Cousin marriage",@"Cow genome",@"Cowper's gland",@"Cowpox",@"Cox-1",@"Cox-1 inhibitor",
    @"Cox-2",@"Cox-2 inhibitor",@"Coxa valga",@"Coxa vara",@"Coxsackievirus",@"CpG",@"CpG island",
    @"Crabs",@"Cracked tooth syndrome",@"Cradle cam",@"Cradle cap",@"Cradle-cam",@"Cradlecam",
    @"Cradlecam",@"Writer's cramp",@"Heat Cramps",@"Menstrual cramps",@"Cranial",@"Cranial arteritis",
    @"Cranial bone",@"Cranial nerve Ⅰ",@"Cranial nerve Ⅱ",@"Cranial nerve　Ⅲ",@"Cranial nerve Ⅳ",
    @"Cranial nerve Ⅸ",@"Cranial nerve Ⅴ",@"Cranial nerve Ⅵ",@"Cranial nerve Ⅶ",@"Cranial nerve Ⅷ",
    @"Cranial nerve Ⅹ",@"Cranial nerve Ⅺ",@"Cranial nerve Ⅻ",@"Eighth cranial nerve",@"eleventh cranial nerve",
    @"Fifth cranial nerve",@"First cranial nerve",@"Fourth cranial nerve",@"Ninth cranial nerve",
    @"Second cranial nerve",@"Seventh cranial nerve",@"Sixth cranial nerve",@"Tenth cranial nerve",
    @"Third cranial nerve",@"Twelfth cranial nerve",@"Cranial nerves",@"Cranio-",
    @"Craniocleidodysostosis",@"Craniology",@"Craniometaphyseal dysplasia",@"Craniopagus parasiticus",
    @"Craniopharyngioma",@"Craniosynostosis",@"Craniotomy",@"Cranium",@"Crapulence",@"Crapulent",
    @"Cream",@"Single transverse palmar crease",@"Creatine",@"Creatinine",@"Creatinine clearance test",
    @"Crepitus",@"Cretinism",@"Crib death",@"Crick",@"Francis Crick",@"Crick-Brenner experiment",
    @"Crime scene investigation",@"Cripple",@"Crippled",@"Midlife crisis",@"Critical care",
    @"Crocodile tears syndrome",@"Crohn enteris",@"Crohn enterocolitis",@"Crohn ileitis",
    @"Crohn ileocolitis",@"Cross training",@"Cross-section",@"Cross-sectional study",
    @"Cross-species transplantation",@"Crossed embolism",@"Crossing over",@"Crossover study",
    @"Crotch",@"Crown",@"Cruciate",@"Anterior cruciate ligament",@"Posterior cruciate ligament",
    @"Crush injury",@"Crutch",@"Cry for help",@"Cryo-EM",@"Cryo-electron microscopy",
    @"Cryocardioplegia",@"Cryoelectron microscopy",@"Cryoglobulin",@"Cryoglobulinemia",
    @"Cryophobia",@"Cryopreservation",@"Cryoprobe",@"Cryoprotectant",@"Cryostat",@"Cryosurgery",
    @"Crypt",@"Cryptic",@"Cryptitis",@"Crypto",@"Cryptococcus gattii",@"Cryptococcus neoformans",
    @"Cryptography",@"Cryptorchidism",@"Cryptosporidium",@"Cryptosporidium enteritis",
    @"Cryptosporidium parvum",@"Cubital",@"Cubital tunnel",@"Cubital tunnel syndrome",
    @"Cubitus",@"Cubitus valgus",@"Cubitus varus",@"Cubid bone",@"Cul-de-sac",@"Culdocentesis",
    @"Culdoscope",@"Culdoscopy",@"Culture",@"Optic cup",@"Cupping",@"Curable",@"Curare",
    @"Curcumin",@"Cure",@"Curettage",@"Curette",@"Curettement",@"Curie",@"Ci",@"Currarino syndrome",
    @"Ondine's curse",@"Cushing's ulcer",@"Harvey Cushing",@"Cushingoid",@"Cusp",@"Cut",
    @"Cutaneous",@"Cutaneous allodynia",@"Cutaneous papilloma",@"Cutaneous syndactyly",
    @"Cutis",@"Cutis anserina",@"Cutis laxa",@"Cuts",@"Cutting for the stone",@"Cyanide",
    @"Cyanogen chloride",@"Cyanosis",@"Cyanotic",@"Cell cycle",@"Menstrual cycle",
    @"Cyclic AMP-dependent protein kinase",@"Cyclic citrullinated peptide",@"Cyclic citrullinated peptide antibody",
    @"Cyclic vomiting syndrome",@"Cyclin",@"Cyclin D",@"Cyclin E",@"Cyclobutanone",@"Cyclooxygenase",
    @"Cyclooxygenase inhibitor",@"Cyclooxygenase-1",@"Cyclooxygenase-1 inhibitor",@"Cyclooxygenase-2",
    @"Cyclooxygenase-2 inhibitor",@"Cyclopia",@"Cyclops",@"Cyclospora infection",@"Cyclosporiasis",
    @"Cyclothymia",@"Cyclindroma",@"Familial cylindromatosis",@"Cymbalta",@"Cynophobia",
    @"Cys-Cys",@"Cyst",@"Follicular cyst of the ovary",@"Baker Cyst",@"Meibomian Cyst",
    @"Ovarian cyst",@"Pilonidal cyst",@"Sebaceous cyst",@"Synovial cyst of the popliteal space",
    @"Tarsal cyst",@"Thyroglossal cyst",@"Thyrolingual cyst",@"Cystadenoma",@"Cystatin 3",
    @"Cystatin C",@"Cystectomy",@"Cysteine",@"Cystic periventricular leukomalacia",@"Cysticerci",
    @"Cysticercus",@"Cystine",@"Cystine kidney stones",@"Cystine transport disease",@"Cystinosis",
    @"Cystitis",@"Interstitial cystitis",@"Cystoscope",@"Cyte",@"Cyto",@"Cyto-",@"Cytogenetic map",
    @"Cytogenetics",@"Clinical cytogenetics",@"Cytokine",@"Cytokinesis",@"Cytology",@"Flow cytometry",
    @"Cytoplasm",@"Cytosine(C)",@"Cytosis",@"Cytoskeleton",@"Cytotoxic",@"Cytotoxic T-lymphocyte"];
    [MedicalWordStore addObjectsFromArray:CWord];
    NSArray *DWord = @[@"D&C",@"D(domain)",@"D and C",@"D-",@"D-IBS",@"D-dimer",@"D.O.",@"DBT",@"DCIS",
    @"DDH",@"developmental dislocation of the hip",@"DEA",@"DEB",@"dystrophic epidermolysis bullosa",
    @"DEHP",@"DES",@"DEXA",@"DESP",@"DGS",@"DHA",@"DHEA",@"DHF",@"dengue hemorrhagic fever",
    @"DHHS",@"DHRD",@"DHT",@"DIDMOAD",@"DISH",@"DKKI",@"DLI",@"DM",@"DM1",@"DM2",@"DNA",@"did not attend",
    @"DNA amplification",@"DNA assembly",@"DNA cloning",@"DNA forensics",@"Recombinant DNA molecules",
    @"DNA polymerase",@"DNA repair",@"DNA repair gene",@"Med1 DNA repair gene",@"DNA repair pathway",
    @"DNA replication",@"DNA sequence",@"Draft DNA sequence",@"Finished DNA sequence",
    @"Alternative DNA splicing",@"Recombinant DNA technology",@"DNA virus",@"Coding DNA",
    @"Junk DNA",@"Mitochondrial DNA",@"Nongenetic DNA",@"Repetitive DNA",@"Satellite DNA",
    @"DNR",@"DNS",@"DOB",@"DOC",@"DOE",@"DOTS",@"DPC4",@"DPT",@"DPT immunization",@"DR syndrome",
    @"DRE",@"digital rectal exam",@"DRRS",@"DRVs",@"Daily Reference Values",@"DSCR",@"DSM",
    @"DSM-Ⅳ",@"DSS1",@"DT",@"DT immunization",@"DTC",@"DTP",@"DTaP",@"DTaP immunization",
    @"DV",@"DX",@"DXA",@"DXA bone scan",@"DXM",@"DYS",@"Leonardo Da Vinci",@"Dacry-",
    @"Dacryo-",@"Dacryoadenitis",@"Dacryocyst",@"Dacryocystorhinostomy",@"Dactyl-",@"Dactyledema",
    @"Dactylitis",@"Daily Prayer of a Physician",@"Daily Value",@"Daltonism",@"Dancing mania of Maracaibo",
    @"Dander",@"Danders",@"Dandruff",@"Dandy fever",@"Danlos syndrome",@"Dannie Abse",@"Danon disease",
    @"Darier disease",@"Dark adaptometry",@"Charles Darwin",@"Data",@"Expiration Date",@"Daughter",
    @"David-Stickler syndrome",@"Daw",@"Day sight",@"De Lange syndrome",@"De Musset sign",
    @"Death",@"Death rate",@"Infant death rate",@"Black death",@"Debilitate",@"Debride",
    @"Debridement",@"Debris flow injury",@"Debulk",@"Decease",@"Decompress",@"Decompression",
    @"Biliary Decompression",@"Decongestant",@"Decortication",@"Decubitus",@"Decubitus ulcer",
    @"Deep",@"Deer mouse",@"Deerfly fever",@"Defecation syncope",@"Atrial septal defect",
    @"enzyme defect",@"Neural tube defect",@"Ventricular septal defect",@"Defensin",
    @"Defensive medicine",@"Defibrillation",@"Defibrillator",@"Defibrillator storm",
    @"Automated external defibrillator",@"Implantable cardiac defibrillator",@"FALDH deficiency",
    @"FAO deficiency",@"GALT deficiency",@"LCHAD deficiency",@"UDP-glucuronosytransferase deficiency",
    @"UROD deficiency",@"adenosine deaminase deficiency",@"alpha-1 antitrypsin deficiency",
    @"Alpha-galactosidase A deficiency",@"Ankyrin deficiency",@"Calcium deficiency",
    @"Ceruloplasmin deficiency",@"fatty alcohol",@"NAD+ oxidoreductase deficiency",
    @"Fatty aldehyde dehydrogenase deficiency",@"Glucocerebrosidase deficiency",@"hex-A deficiency",
    @"Hexosaminidase A deficiency",@"Lactase deficiency",@"Magnesium deficiency",
    @"Phenylalanine hydroxylase deficiency",@"Protein C deficiency",@"Selenium deficiency",
    @"Sphingomyelinase deficiency",@"Uroporphyrinogen decarboxylase deficiency",
    @"Vitamin K deficiency",@"Zinc deficiency",@"Deformation",@"Klippel-Feil Deformity",
    @"Macular degeneration",@"Degenerative joint disease",@"Deglutition",@"Dehisce",
    @"Dehydroepiandrosterone",@"Deinococcus rediodurans",@"Deja vu",@"Dejerine-Klumpke palsy",
    @"Dejerine-Klumpke paralysis",@"Developmental delay",@"Deletion",@"Delirium",@"Delirium tremens",
    @"Breech delivery",@"Footling delivery",@"Vertex delivery",@"Della Robbia",@"Pancreatic delta cell",
    @"Delta-storage pool disease",@"Deltoid",@"Delusion",@"Delusional jealousy",@"Delusional parasitosis",
    @"Demarcation",@"Demonophobia",@"Demulcent",@"Demyelination",@"Dendrite",@"Dendritic",
    @"Dendritic cell",@"Denervate",@"Denervation",@"Dengue",@"Dengue hemorrhagic fever",
    @"DHF",@"American dental association",@"ADA",@"National Inst. Dental and Craniofacial Research",
    @"Dental drill",@"Dental impaction",@"Dentin",@"Deoxyhemoglobin",@"Deoxyribonucleic acid",
    @"Department of Energy",@"DOE",@"Department of Health and Human Services",@"Depigmentation",
    @"Depo-Provera contraceptive",@"Dercum disease",@"Dermal",@"Dermatan sulfate",
    @"Dermatitis",@"Atopic dermatitis",@"Stasis Dermatitis",@"Dermatofibroma",
    @"Dermatofibrosarcoma protuberans",@"Dermatoglyphic",@"Dermatoglyphics",@"Dermatographism",
    @"Dermatologic",@"Dermatologist",@"Dermatology",@"Dermatome",@"Dermatomyositis",
    @"Dermatopathy",@"Dermatophytic onychomycosis",@"Dermatoscopy",@"Dermicidin",@"Dermis",
    @"Dermoid",@"Dermoid cyst of the ovary",@"Dermopathy",@"Diabetic dermopathy",@"Descending aorta",
    @"Descending pathway",@"Desert fever",@"Desiccate",@"Designer estrogen",@"Designer steroid",
    @"Desmoid tumor",@"Desmoplasia",@"Desmoplastic",@"Desmoplastic reaction",@"Desquamate",
    @"Desquamation",@"Detox",@"Detoxify",@"Deuteranomaly",@"Deuteranopia",@"Deuterium",
    @"Development",@"NICHD",@"Development delay",@"Developmental dislocation of the hip",
    @"DDH",@"Developmental disorder",@"Specific developmental disorder",@"Developmental dyspraxia",
    @"Deviation of the nasal septum",@"Assistive device",@"Medical device",@"Dextro-",
    @"Dextrocardia",@"Dextromethorphan",@"Dextroposition",@"Dextroposition of the heart",
    @"Dextrose",@"Di-",@"DiGeorge syndrome",@"Dia-",@"Diabesity",@"Diabetes",@"American Diabetes Association",
    @"Diabetes and Digestive and Kidney Disease",@"NIDDK",@"Diabetes skin condition",
    @"Adult-onset diabetes",@"Brittle diabetes",@"gestational diabetes",@"Juvenile diabetes",
    @"Juvenile-onset diabetes",@"Ketosis-prone diabetes",@"Labile diabetes",@"Type 1 diabetes",
    @"Type 2 diabetes",@"Unstable diabetes",@"Diabetic dermatology",@"Diabetic dermopathy",
    @"Diabetic eye disease",@"Diabetic ketoacidosis",@"Diabetic musculoskeletal disorder",
    @"Diabetic nephropathy",@"Dabetic retinopathy",@"Diabetic spinal cord disease",
    @"Diabetic xanthoma",@"Diabulimia",@"Diacetyl",@"Diachronic",@"Diachronic study",@"Diagnosis",
    @"Differential diagnosis",@"Retrospective diagnosis",@"Dialectical behavioral therapy",
    @"Diaphragmatic pacing",@"Diastole",@"Diastolic",@"Diastrophic dysplasia",@"Diathermy",
    @"Diathesis",@"Dibenzoxazepine",@"Dicentric chromosome",@"Dicysteine",@"Diesel exhaust",
    @"Diesel exhaust particle",@"Atkins Diet",@"DASH Diet",@"Mediterranean Diet",@"Diethylstilbestrol",
    @"Diff dx",@"Differential diagnosis",@"Differential white cell count",@"Differentiation",
    @"Differentiation therapy",@"Difficult urination",@"Diffuse cutaneous mastocytosis",
    @"Diffuse mastocytosis",@"Diffuse toxic goiter",@"Nat'l Inst Diabetes and Digestive a Kidney Dis",
    @"Digit",@"Supernumerary digit",@"Digital rectal exam",@"Dihydroorotate dehydrogenase",
    @"Dihydrotestosterone",@"Dihydroxyacetone",@"Dilatate",@"Dilatation",@"Dilate",@"Dilating",
    @"Dilation",@"Pupil dilation",@"Pupil dilation test",@"Dilator",@"Dinucleotide",@"Dioscorides",
    @"Dioxin",@"Paraffin dip",@"Wax dip",@"Dipeptide",@"Diploe",@"Diploid",@"Diplopia",@"Binocular diplopia",
    @"Monocular diplopia",@"Dipper",@"Diprosopus",@"Dipsophobia",@"Dipsosis",@"Direct-entry midwife",
    @"Directed DNA sequencing",@"Advance directives",@"Advance medical directives",@"Dirofilaria immitis",
    @"Disc",@"Cervical disc",@"Optic disc",@"Slipped disc",@"Discharge",@"Nipple discharge",
    @"Discoid lupus",@"Discordance",@"Discordant",@"Discordant couple",@"Disease",@"Disease names",
    @"Disease nomenclature",@"Disease surveillance",@"Addison disease",@"Alexander Disease",
    @"Alpers Disease",@"Alzheimer Disease",@"Anderson-Fabry Disease",@"Behcet's Disease",
    @"Bernard-Soulier Disease",@"Binswanger Disease",@"Bornholm Disease",@"Bowen's Disease",
    @"Bright's Disease",@"Brill-Zinsser Disease",@"Canavan Disease",@"Castleman Disease",
    @"Chagas Disease",@"Charcot-Marie-Tooth Disease",@"Conor and Bruch Disease",@"Creutzfeldt-Jakob Disease",
    @"Cushing Disease",@"Fabry Disease",@"Fahr Disease",@"Fong Disease",@"Forestier Disease",
    @"Gaucher type 1 disease",@"Gerstmann-Straussler-Scheinker Disease",@"Gilbert Disease",
    @"Graves Disease",@"Hansen Disease",@"Heberden Disease",@"Hirschsprung Disease",@"His Disease",
    @"His-Werner Disease",@"Hodgkin Disease",@"Hodgkin lymphoma",@"Hodgkin lymphoma",@"Hodgkin Disease",
    @"Huntington Disease",@"Jakob's Disease",@"Jakob-Creutzfeldt Disease",@"Kawasaki Disease",
    @"Keshan Disease",@"Kikuchi Disease",@"Kimmelstiel-Wilson Disease",@"Kok Disease",
    @"Kostmann Disease",@"Legg Disease",@"Legg-Calve-Perthes Disease",@"Legg-Perthes Disease",
    @"Legionnaire Disease",@"Lobstein's Disease",@"Lou Gehrig Disease",@"Marburg Disease",
    @"Menetrier's Disease",@"Meniere Disease",@"Minamata Disease",@"Niemann-Pick Disease",
    @"Norwalk Disease",@"Osgood-Schlatter Disease",@"Osler-Rendu-Weber Disease",@"Parkinson Disease",
    @"Parry's Disease",@"Pelizaeus-Merzbacher Disease",@"Pick Disease",@"Plummer's Disease",
    @"Quincke's Disease",@"Ramsay Hunt Disease",@"Refsum Disease",@"Rendu-Osler-Weber Disease",
    @"Ritter Disease",@"Stein-Leventhal Disease",@"Still Disease",@"Takayasu Disease",@"Tay-Sachs Disease",
    @"Tsutsugamushi Disease",@"Vrolik's Disease",@"Werner-His Disease",@"Whipple Disease",
    @"Whitmore's Disease",@"Wilson Disease",@"Acute respiratory disease",@"Adult Celiac Disease",
    @"Alveolar hydatid disease",@"Autoimmune disease",@"Bipolar Disease",@"Black lung disease",
    @"Cardiovascular Disease",@"Cat scratch disease",@"Chronic obstructive lung disease",
    @"COLD",@"Chronic wasting disease",@"Clinical disease",@"Cogenital heart disease",
    @"Coronary artery disease",@"Cystine transport disease",@"Degenerative joint disease",
    @"Delta-storage pool disease",@"Exaggerated startle disease",@"Fifth disease",@"Foot-and-mouth disease",
    @"Graft-versus-host disease",@"guinea worm disease",@"Gum disease",@"Hand-foot-and-mouth disease",
    @"Hemolytic disease of the newborn",@"Hyaline membrane disease",@"Inflammatory bowel disease",
    @"Kissing disease",@"Lipid storage disease",@"Mad deer disease",@"Manic-depressive disease",
    @"Maple syrup urine disease",@"Mitochondrial disease",@"Mixed connective tissue disease",
    @"New variant Creutzfeldt-Jakob disease",@"Occupational disease",@"Phytanic acid storage disease",
    @"Polycystic kidney disease",@"Polycystic ovarian disease",@"Polygenic Disease",@"Pulseless Disease",
    @"Rheumatic heart disease",@"Sigle gene disease",@"Sixth Disease",@"Sleeping Disease",
    @"Startle disease",@"Subclinical disease",@"Variant Creutxfeldt-Jakob disease",
    @"von Recklinghausen disease",@"Disease-free survival",@"Diseases related to obesity",
    @"inherited metabolic disease",@"Rickettsial disease",@"Disinsection",@"Intervertebral Disk",
    @"Dislocation of the radial head",@"Congenital hip dislocation",@"Articulation disorder",
    @"Attention deficit disorder",@"Autoimmune disorder",@"Bipolar disorder",@"Borderline personality disorder",
    @"Central auditory processing disorder",@"Cephalic disorder",@"Mathematics disorder",
    @"Orgasmic disorder",@"Seasonal affective disorder",@"Specific developmental disorder",
    @"Disordered thinking",@"Lymphoproliferative disorders",@"Myeloproliferative disorders",
    @"Disruption sequence",@"Dissect",@"Dissecting aneurysm",@"Dissection",@"Aortic dissection",
    @"Axillary dissection",@"Neck Dissection",@"Raical neck dissection",@"Disseminated sclerosis",
    @"Disseminated vaccinia",@"Dissociation",@"Distal",@"Distance healing",@"Distention",
    @"Distichiasis",@"Disto-",@"Diuresis",@"Diuretic",@"Diurnal",@"Diverticula",@"Diverticulitis",
    @"Bleeding from diverticulitis",@"Treatment of acute diverticulitis",@"Diverticulum",
    @"Meckel's diverticulum",@"Zenker diverticulum",@"Hypopharyngeal diverticulum",
    @"Pharyngoesophageal diverticulum",@"Diving injury",@"Dizygotic twin",@"Pre-syncopal dizziness",
    @"Do not resuscitate order",@"Dobelle",@"William H. Dobelle",@"Doc",@"Docosahexaenoic acid",
    @"Doctor",@"Doctor discontent",@"Doctor Without Borders",@"Doctor's symbol",@"Dog genome",
    @"Dog heartworm",@"Dol",@"Dolor",@"Gerhard Domagk",@"Domain",@"Dominant",@"Autosomal dominant",
    @"Donald Fredrickson",@"Donor",@"Donor insemination",@"Donor lymphocyte infusion",
    @"Universal donor",@"Dopa",@"Dopamine",@"Doraphobia",@"Dorian Gray effect",@"Dorothy Hodgkin",
    @"Dorsal",@"Dorsum",@"Absorbed dose",@"Double helix",@"Double-blind",@"Double-blinded study",
    @"Double-jointed",@"Double-masked",@"Pouch of douglas",@"Doula",@"Dowager's hump",
    @"Down-regulation",@"Downregulation",@"Doxorubicin cardiomyopathy",@"Sir Arthur Conan Doyle",
    @"Doyne honeycomb retinal dystrophy",@"Dr. Andrew Weil",@"Dr. Joseph Moscati",@"Dracunculiasis",
    @"Draft DNA sequence",@"Drain",@"JP Drain",@"Jackson Pratt Drain",@"Jackson-Pratt Drain",
    @"Penrose Drain",@"Dreams",@"Dressler syndrome",@"Dental drill",@"Drip",@"Drop attack",
    @"Dropsy",@"Drosophila",@"Drosophila genome",@"Drug Enforcement Administration",@"DEA",
    @"Drug activity",@"Drug resistance",@"Drug test",@"ACE-inhibitor drug",@"Anti-infective drug",
    @"Antibiotic drug",@"Antifungal drug",@"Antihypertensive drug",@"Antimicrobial drug",
    @"Antiprotozoal drug",@"Antithyroid drug",@"Antiviral drug",@"Generic drug",@"Over-the-counter drug",
    @"OTC",@"Precription drug",@"Sulfa drug",@"Tocolytic drug",@"Drug-transporter gene",
    @"Anti-angiogenesis drug",@"Statin drugs",@"Teratogenic drugs",@"Drunkorexia",@"Drusen",
    @"Dual X-ray absorptometry",@"Dual energy X-ray absorptometry",@"Duane retraction syndrome",
    @"Duane syndrome",@"Duane-radial ray syndrome",@"Duchenne muscular dystrophy",
    @"Duchenne-Erb palsy",@"Duchenne-Erb paralysis",@"Duct",@"Duct of Bellini",@"Ejaculatory duct",
    @"Hepatic duct",@"Ductal carcinoma in situ",@"Syndromatic hepatic ductular hypoplasia",
    @"Ductus",@"Ductus arteriosus",@"Patent ductus",@"Due date",@"Dumdum fever",@"Dummy",
    @"Dumping syndrome",@"Duodenal",@"Duodenal ulcer",@"Duodenitis",@"Duodenum",@"Duplication",
    @"Guillaume Dupuytren",@"Dura",@"Dura mater",@"Durable power of attorney",@"Dural",
    @"Dural sac",@"Dursban",@"Dust mite",@"Dutch-Kentucky syndrome",@"Dwarf",@"Dwarfism",
    @"Achondroplastic dwarfism",@"Pituitary dwarfism",@"Thanatophoric dwarfism",@"Dx",
    @"Dyad",@"Dynacin",@"Dynein",@"Dys-",@"Dysarthria",@"Dyscalculia",@"Dyscrasia",@"Dysentery",
    @"Amebic dysentery",@"Dysfunction",@"Orgasmic dysfunction",@"Dysgraphia",@"Dyskeratosis congenita",
    @"Dyskinesia",@"Dyslipidemia",@"Dysmetabolic syndrome X",@"Dysmorphic feature",
    @"Dysmorphology",@"Dysmorphophobia",@"Dysmotility syndrome",@"Cleidocranial dysostosis",
    @"Dyspareunia",@"Dyspeptic",@"Dysphagia",@"Dysphasia",@"Dysphonia",@"Spasmodic dysphonia",
    @"Spastic Dysphonia",@"Dysphoria",@"Dysphoric mania",@"Dysplasia",@"Arteriohepatic dysplasia",
    @"Bronchopulmonary dysplasia",@"Cleidocranial dysplasia",@"Congenital hip dysplasia",
    @"Faciodigitogenital dysplasia",@"Faciogenital dysplasia",@"Thanatophoric dysplasia",
    @"Dysplastic nevi",@"Dysplastic nevus",@"Dyspnea",@"Dyspnoea",@"Dyspraxia",@"Dyspraxia of speech",
    @"Developmental dyspraxia",@"Dystocia",@"Cervical dystocia",@"Fetal dystocia",@"Placemental Dystocia",
    @"Shoulder dystocia",@"Dystrophia brevicollis cogenita",@"Dystrophic epidermolysis bullosa",
    @"Dystrophica myotonia",@"Dystrophica myotonia 2",@"Autoimmune polyendocrinopathy dystrophy",
    @"Cone dystrophy",@"Corneal dystrophy",@"Lattice dystrophy",@"Muscular dystrophy",
    @"Myotonic dystrophy",@"Dysuria"];
    [MedicalWordStore addObjectsFromArray:DWord];
    NSArray *EWord = @[@"E.coli",@"E2F transcription factor 3",@"E2F3",
                       @"EB",@"Epidermolysis bullosa",@"EBA",@"epidermolysis bullosa acquisita",@"EBM",
                       @"EBS",@"epidermolysis bullosa simplex",@"EBV",@"EC",@"ECMO",@"ECST",@"ECT",@"ECoG",
    @"ECochG",@"EDC",@"EDMD",@"EDS",@"excessive daytime sleepiness",@"EECP",@"EEE",@"EFEMP1",
    @"EGD",@"EGF",@"EGFR",@"ELA2",@"ELBW",@"ELISA",@"EM",@"electron microscope",
    @"EMG",@"EMG syndrome",@"Surface EMG",@"EMSY",@"EMT",@"ENGERIX-B",@"ENT",@"ENT physician",
    @"EOG",@"EOS",@"EPA",@"EPO test",@"EPR",@"EPS",@"EPT",@"ER",@"ERG",@"ERISA",@"ERT",
    @"Estrogen replacement therapy",@"ESR",@"ESRD",@"EST",@"Expressed sequence tag",
    @"ESWL",@"ET",@"ETM1",@"ETM2",@"ETS",@"EUS",@"EVAR",@"EXIT",@"EYCL1",@"EYCL2",@"EYCL3",
    @"Eagle syndrome",@"Ear",@"Ear bones",@"Self-cleaning ear canal",@"Ear cleaning by a doctor",
    @"Ear cleaning yourself",@"Ear drum",@"Ear piercing",@"Ear pit",@"Ear puncture",@"Ear ringing",
    @"Ear tag",@"Ear thermometer",@"Cauliflower ear",@"External ear",@"Foreign object in ear",
    @"Inner ear",@"Internal ear",@"Low-set ear",@"Malrotated ear",@"Middle ear",@"Outer ear",
    @"Slanted ear",@"Earache",@"Eardrum",@"Early-onset familial Alzheimer disease",
    @"Eastern equine encephalitis",@"Eat Right 4 Your Type Diet",@"Ebola virus",@"Ecchymosis",
    @"Ecchymotic",@"Echinacea",@"Echinococcosis",@"Echinococcus",@"Echocardiography",
    @"Transesophageal echocardiography",@"Echolalia",@"Echopraxia",@"Echovirus",@"Eclosion",
    @"Ecogenetics",@"Economy class syndrome",@"Ectoderm",@"Ectodermal",@"Ectodermal dysplasia",
    @"Ectodermosis erosiva pluriorficialis",@"Ectomy",@"Ectoparasite",@"Ectoparasitosis",
    @"Ectopia cordis",@"Ectopic",@"Ectrodactyly",@"Ectromelia virus",@"Ed Lewis",@"Edentulism",
    @"Edentulous",@"Edward B.Lewis",@"Edwards syndrome",@"Effacement",@"Founder effect",
    @"Effective dose",@"Fetal rubella effects",@"Efferent",@"Efferent nerve",@"Efferent vessel",
    @"Effusion",@"Pericardial effusion",@"Pleural effusion",@"Egg",@"Egg donor",@"Egg sac",
    @"Paul Ehrlich",@"Ehrlichiosis",@"Eicosanoid",@"Eicosapentaenoic acid",@"Eidetic",
    @"Eight-day measles",@"Eighth cranial nerve",@"Eileithyia",@"Eisoptrophobia",@"Ejaculate",
    @"Ejaculation",@"Ejaculatory duct",@"Ejection fraction",@"Elastase",@"Elastase 1",
    @"Elastase 2",@"Elastase inhibitor",@"Elasticin",@"Elastin",@"Elastin degrading enzyme",
    @"Elavil",@"Elbow",@"Elbow dislocation",@"Elbow joint",@"Elbow subluxation",@"Golfer's elbow",
    @"Tennis elbow",@"Tip of the elbow",@"Elder abuse",@"Elective",@"Elective mutism",@"Elective surgery",
    @"Electro-oculography",@"Electrocoagulation",@"Electrocochleography",@"Electrodesiccation",
    @"Electrolarynx",@"Electrolyte",@"Electromagnetic field thrapy",@"Electron microscope",
    @"Electron microscopy",@"Electronystagmogram",@"Electrophoresis",@"Electrophoretic",
    @"Electrophrenic respiration",@"Electrophysiologic",@"Electrophysiologic retinal testing",
    @"Electrophysiologic study of the heart",@"Electrophysiologic testing of the retina",
    @"Electrophysiology",@"Electroretinogram",@"Electroshock therapy",@"Electrosurgery",
    @"Elephantiasis",@"Elevated hemidiaphragm",@"Eleventh cranial nerve",@"Elizabeth Blackwell",
    @"Elizabeth Kubler-Ross",@"Elliptocytosis",@"Ellis-van Creveld syndrome",@"Emboli",@"Embolism",
    @"Fat Embolism",@"Crossed Embolism",@"Paradoxical Embolism",@"Pulmonary Embolism",
    @"Embolization",@"Embolus",@"Embryo",@"Embryonal carcinoma",@"Emergency code",@"Emergency contraception",
    @"Emergency department",@"Emergency medical technician",@"Emergency physician",
    @"Emergency postcoital contraception",@"Emerging infectious disease",@"Emery-Dreifuss muscular dystrophy",
    @"Emesis",@"Emetic",@"Emetophobia",@"Emia",@"Empiric risk",@"Empirical",@"Empirical midwife",
    @"Employment Retirement Income Security Act",@"Empyema",@"Enanthem",@"Enate",@"Encapsulated",
    @"LAC Encephalitis",@"LaCrosse Encephalitis",@"Nipah virus Encephalitis",@"Rasmussen Encephalitis",
    @"St.Louis Encephalitis",@"West Nile Encephalitis",@"Arboviral encephalitis",@"Eastern equine encephalitis",
    @"Flavivirus encephalitis",@"Viral encephalitis",@"Encephalomyelitis",@"Encephalopathic syndrome",
    @"Mitochondrial encephalopathy",@"MELAS",@"Enchondromatosis",@"End stage",@"End-of-life assistant",
    @"End-of-life companion",@"End-of-the-road disease",@"End-stage renal disease",@"Endarterectomy",
    @"Endemic",@"Endep",@"Endocannabinoid",@"Endocardinal",@"Endocarditis",@"Endocardium",
    @"Endocervical curettage",@"Endochondral bone",@"Endocrine",@"Endocrine gland",@"Endocrinology",
    @"Endocrinopathy",@"Endoderm",@"Endodermal",@"Endogenous",@"Endometrial hyperplasia",
    @"Endometrioid cyst",@"Endometrioma",@"Endometritis",@"Endometrium",@"Endonuclease",
    @"Endopeptidase",@"Endoplasmic reticulum",@"Endorectal MRI",@"Endorphin",@"Endoscope",
    @"Percutaneous endoscopic gastrostomy",@"PEG",@"Endoscopic papillotomy",
    @"Endoscopic retrograde cholangiopancreatography",@"Endoscopic sphincterotomy",
    @"Endostatin",@"Endothelial",@"Endothelial progenitor cell",@"Endothelium",@"Endotherm",
    @"Endotracheal tube",@"Endourologist",@"Endovascular aneurysm repair",@"Enediyne",
    @"Enema",@"Barium enema",@"Enervate",@"Enervation",@"Enfeeble",@"Engagement",@"Engram",
    @"Enhanced external counterpulsation",@"Enkephalinase",@"Enlarged heart",@"Enlarged thyroid",
    @"Enophthalmos",@"Entamoeba histolytica",@"Enteral",@"Enteric",@"Enteric-coated",@"Crohn Enteritis",
    @"Regional Enteritis",@"Entero-",@"Enterobiasis",@"Enterocele",@"Enterococcus",@"Crohn Enterocolitis",
    @"Enteropathy",@"Gluten enteropathy",@"Protein-losing enteropathy",@"Enteroplasty",
    @"Enteroscopy",@"Enterospasm",@"Enterostomal therapist",@"Enterostomy",@"Enterovirus",
    @"Entomology",@"Medical entomology",@"Entomophobia",@"Enucleation",@"Enuresis",@"Environment",
    @"Environmental Protection Agency",@"Environmental medicine",@"Environmental tobacco smoke",
    @"Environmental toxicology",@"Enzootic",@"Enzyme",@"Enzyme defect",@"Enzyme replacement",
    @"Warburg's yellow enzyme",@"Lysosomal enzyme",@"Restriction enzyme",@"Enzyme-linked immunosorbent assay",
    @"ELISA",@"Enzymes",@"Yellow enzymes",@"Eosinophil",@"Eosinophilia",@"Familial eosinophilia",
    @"Eosinophilic leukocyte",@"Eosinophilic meningitis",@"Ependymoma",@"Ephedra",@"Ephelides",
    @"Ephelis",@"Epi-",@"Epicanthal fold",@"Epicardium",@"Epicondylitis",@"Lateral epicondylitis",
    @"Epidemic",@"Epidemic hemorrhagic fever",@"Epidemic myalgia",@"Epidemic scorecard",
    @"Epidemiologist",@"Classical epidemiology",@"Clinical Epidemiology",@"Epidermal",
    @"Epidermal growth factor",@"Epidermal growth factor receptor",@"Epidermis",@"Epidermoid carcinoma",
    @"Epidermolysis bullosa",@"Epidermolysis bullosa acquisita",@"Epidermolysis bullosa simplex",
    @"Epididymis",@"Epididymitis",@"Epidural",@"Epidural anesthetic",@"Epigastrium",@"Epigenetic",
    @"Epigenetics",@"Epiglottis",@"Acute epiglottitis",@"Epilation",@"Epilepsy",@"Jacksonian Epilepsy",
    @"Grand mal epilepsy",@"Juvenile myoclonic epilepsy",@"Partial epilepsy",@"Petit mal epilepsy",
    @"Temporal lobe epilepsy",@"Temporal-lobe epilepsy",@"Epinephrine",@"Epiphenomenon",
    @"Epiphysis",@"Epiretinal membrane",@"Episclera",@"Episcleritis",@"Epispadias",@"Epistaxis",
    @"Treatment of epistaxis",@"Epistemic",@"Epithelial",@"Epithelial basement corneal dystrophy",
    @"Epithelial carcinoma",@"Epithelium",@"Epitope",@"Epizootic",@"Eponym",@"Epsom salt",
    @"Epstein-Barr virus",@"Equinophobia",@"Equol",@"Erb palsy",@"Erb paralysis",@"Erb's palsy",
    @"ErbB",@"ErbB1",@"Penile Erection",@"Ergonomics",@"Ergophobia",@"Ergot",@"Ergotism",
    @"Erosion",@"Erotic jealousy syndrome",@"Erotomania",@"Error of the first kind",
    @"Error of the second kind",@"Alpha error",@"Beta error",@"type Ⅰ error",@"type Ⅱ error",
    @"Inborn errors of metabolism",@"Eructation",@"Bather's eruption",@"Eruptive xanthoma",
    @"Erythema",@"Erythema chronicum migrans",@"Erythema dose",@"Erythema infectiosum",
    @"Erythema multiforme",@"Erythrasma",@"Erythrocyanosis",@"Erythrocyte",
    @"Erythrocyte membrane protein band 4.1",@"EPB41",@"Erythroleukemia",@"Erythrophobia",
    @"Erythroplakia",@"Erythroprosopalgia",@"Eschar",@"Excherichia coli",@"Eskalith",@"Esophageal",
    @"Esophageal acid infusion test",@"Esophageal reflux",@"Esophageal speech",
    @"Acute esophageal stricture",@"Chronic esophageal stricture",@"Esophageal ulcer",
    @"Esophagectomy",@"Esophagogastric temponade",@"Esophagogastroduodenoscopy",@"Esophagoscopy",
    @"Esophagram",@"Esophagus",@"Esotropia",@"Essential",@"Essential fatty acid",@"Essential oil",
    @"Essential vulvodynia",@"Estimated date of confinement",@"EDC",@"Estrogen",
    @"Estrogen replacement thrapy"];
    [MedicalWordStore addObjectsFromArray:EWord];
    return MedicalWordStore;
}

@end
